/* Native structured document editor. No HTML imports, placeholder strings or eval. */
(() => {
'use strict';
const scText=window.SchemaCraftI18n?.t||((source,...values)=>Array.isArray(source)?source.map((part,i)=>part+(i<values.length?String(values[i]):'')).join(''):String(source));
const displayLabel=(entity,key='label')=>window.SchemaCraftI18n?.display(entity,key)??String(entity?.[key]??'');
const displaySchemaName=entity=>window.SchemaCraftI18n?.display({...entity,name:entity?.name||entity?.schema_name||''},'name')??String(entity?.name||entity?.schema_name||'');
const host=document.getElementById('advanced-export-panel');if(!host)return;host.classList.add('document-writer-host');
const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n;};
const clone=x=>JSON.parse(JSON.stringify(x)),uid=()=> 'n'+crypto.randomUUID().replaceAll('-','');
const names={component:scText('مكوّن مرتبط'),paragraph:scText('فقرة'),heading:scText('عنوان'),section:scText('قسم'),row:scText('صف تخطيط'),divider:scText('خط فاصل'),spacer:scText('مسافة'),pagebreak:scText('فاصل صفحة'),toc:scText('فهرس تلقائي'),image:scText('صورة / شعار'),repeat:scText('مكرر'),table:scText('جدول'),chart:scText('رسم بياني'),calculation:scText('حساب'),percentage:scText('شريط نسبة')};
let model=null,saved=null,catalog=[],library={},active=null,tokenIndex=null,zone='blocks',timer=null,validationTimer=null,saveQueue=Promise.resolve(),epoch=0,loaded=false,undo=[],redo=[],selectionRange=null,lastRun=null,ribbonTab='home',editorExpanded=false,ribbonCollapsed=false,leftCollapsed=false,rightCollapsed=false;
const propertyOpenState=new Map();
const root=el('section','','document-writer dialog-content');root.id='document-writer';
const editor=el('dialog','','editor-dialog writer-editor-dialog');editor.id='writer-editor-dialog';editor.dir='rtl';editor.setAttribute('aria-labelledby','writer-editor-title');
const editorHeading=el('div','','dialog-heading writer-editor-heading'),editorTitle=el('h2',scText('محرر المستندات'));editorTitle.id='writer-editor-title';
const editorHeadingActions=el('div','','writer-editor-heading-actions');
const editorInfo=iconButton('info',scText('معلومات وطريقة إنشاء التقرير'),reportHelp,'writer-window-control writer-window-info');
const editorExpand=iconButton('maximize',scText('توسيع المحرر إلى ملء الشاشة'),toggleEditorSize,'writer-window-control');
const editorClose=iconButton('close',scText('حفظ وإغلاق المحرر'),closeEditor,'dialog-close writer-window-control writer-window-close');
editorHeadingActions.append(editorInfo,editorExpand,editorClose);editorHeading.append(editorTitle,editorHeadingActions);editor.append(editorHeading,root);document.body.append(editor);
const editorFooter=el('div','','dialog-actions writer-editor-footer');editorFooter.append(el('span',scText('تُحفظ المسودة تلقائيًا أثناء الكتابة.'),'writer-hint'),button(scText('حفظ وإغلاق'),closeEditor));editor.append(editorFooter);
const landing=el('section','','writer-launch'),landingText=el('div'),launchButton=button(scText('فتح محرر المستندات'),openEditor),landingStatus=el('p','','writer-hint');
launchButton.className='button button-primary';launchButton.id='writer-open-editor';launchButton.setAttribute('aria-haspopup','dialog');launchButton.setAttribute('aria-controls',editor.id);
landingText.append(el('h3',scText('التقارير المتقدمة')),el('p',scText('اكتب تقريرًا، وأدرج حقولًا وجداول من بياناتك، ثم راجع النتيجة وأنشئ PDF.'),'muted-text'),landingStatus);const landingActions=el('div','','writer-launch-actions');landingActions.append(launchButton,button(scText('تقرير جديد'),starterDialog));landing.append(landingText,landingActions);const dashboard=el('section','','writer-dashboard'),dashboardTabs=el('nav','','writer-dashboard-tabs'),dashboardBody=el('div','','writer-dashboard-body');dashboard.append(dashboardTabs,dashboardBody);const workflowHeading=host.querySelector(':scope > .workflow-collapse-heading')||el('div','','section-title-line');
workflowHeading.classList.add('writer-workflow-heading');workflowHeading.replaceChildren(el('h3',scText('التقارير المتقدمة')));
// Keep the native collapse listener installed on the existing panel heading.
landingText.querySelector('h3')?.remove();
const workflowBody=el('div','','writer-workflow-body');workflowBody.append(landing,dashboard);host.replaceChildren(workflowHeading,workflowBody);let landingTab='templates';
let closingEditor=false,initializing=null;
async function openEditor(){await init();if(!model)return;if(!editor.open)editor.showModal();fitPages();top.querySelector('input')?.focus();}
async function closeEditor(){if(closingEditor)return;closingEditor=true;editorClose.disabled=true;root.inert=true;try{if(model)await save();library=await call('list');renderLandingOverview();editor.close();landingStatus.textContent=model?model.title+scText(' · المسودة محفوظة'):'';launchButton.focus();}catch(e){message(scText('تعذّر حفظ المسودة. بقي المحرر مفتوحًا: ')+e.message,true);}finally{closingEditor=false;editorClose.disabled=false;root.inert=false;}}
function toggleEditorSize(){editorExpanded=!editorExpanded;editor.classList.toggle('is-fullscreen',editorExpanded);setIconButton(editorExpand,editorExpanded?'restore':'maximize',editorExpanded?scText('استعادة حجم النافذة'):scText('توسيع المحرر إلى ملء الشاشة'));requestAnimationFrame(fitPages);}
editor.addEventListener('cancel',e=>{e.preventDefault();closeEditor();});
const top=el('header','','writer-top'),format=el('div','','writer-format'),layout=el('div','','writer-layout'),left=el('aside','','writer-sidebar'),stage=el('main','','writer-stage'),right=el('aside','','writer-sidebar writer-properties'),problems=el('details','','writer-problems'),status=el('span',scText('جاهز'),'writer-status');
root.append(top,format,layout,problems);layout.append(left,stage,right);problems.open=true;
status.setAttribute('role','status');status.setAttribute('aria-live','polite');left.setAttribute('aria-label',scText('الإدراج ومخطط المستند'));right.setAttribute('aria-label',scText('خصائص العنصر'));stage.setAttribute('aria-label',scText('صفحات المستند'));
function pageMm(){const sizes={A4:[210,297],A3:[297,420],Letter:[215.9,279.4],Legal:[215.9,355.6]};let [w,h]=sizes[model?.page?.size||'A4']||sizes.A4;if(model?.page?.orientation==='landscape')[w,h]=[h,w];return [w,h];}
function fitPages(){const available=stage.clientWidth-32,[w]=pageMm();if(available>0)stage.style.setProperty('--writer-zoom',Math.min(1,available/(w*96/25.4)));}
if(typeof ResizeObserver!=='undefined')new ResizeObserver(fitPages).observe(stage);window.addEventListener('resize',fitPages);
async function api(data){const r=await fetch('/api/reports',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const j=await r.json();if(!r.ok)throw Error(j.error||scText('تعذرت العملية'));return j;}
const call=(action,data={})=>api({action:'writer_'+action,...data});
function message(text,error=false){status.textContent=text;status.classList.toggle('is-error',error);if(!editor.open)landingStatus.textContent=text;}
function button(text,fn){const b=el('button',text,'button button-secondary');b.type='button';if(text.startsWith('● '))b.setAttribute('aria-current','step');if(text==='↑'||text==='↓')b.setAttribute('aria-label',text==='↑'?scText('تحريك العنصر إلى أعلى'):scText('تحريك العنصر إلى أسفل'));b.onclick=async()=>{b.disabled=true;try{await fn();}catch(e){message(e.message,true);const d=b.closest('.writer-dialog');if(d){let notice=d.querySelector('.writer-dialog-error');if(!notice){notice=el('p','','writer-dialog-error');notice.setAttribute('role','alert');d.append(notice);}notice.textContent=e.message;notice.scrollIntoView({block:'nearest'});}}finally{b.disabled=false;}};return b;}
function iconSvg(name){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('aria-hidden','true');svg.classList.add('writer-ui-icon');const add=(tag,attrs)=>{const n=document.createElementNS(ns,tag);for(const [k,v] of Object.entries(attrs))n.setAttribute(k,v);svg.append(n);};const line=(x1,y1,x2,y2)=>add('line',{x1,y1,x2,y2});if(name==='info'){add('circle',{cx:12,cy:12,r:8.5});add('circle',{cx:12,cy:8,r:0.9,fill:'currentColor',stroke:'none'});line(12,11,12,16);}
else if(name==='maximize')add('rect',{x:5,y:5,width:14,height:14,rx:1.7});
else if(name==='restore'){add('rect',{x:7,y:7,width:11,height:11,rx:1.4});add('path',{d:'M9 7V5.5A1.5 1.5 0 0 1 10.5 4H18a2 2 0 0 1 2 2v7.5A1.5 1.5 0 0 1 18.5 15H18'});}
else if(name==='close'){line(7,7,17,17);line(17,7,7,17);}
else if(name==='chevron-up')add('path',{d:'M6.5 14.5 12 9l5.5 5.5'});
else if(name==='chevron-down')add('path',{d:'M6.5 9.5 12 15l5.5-5.5'});
else if(name==='chevron-left')add('path',{d:'M14.5 6.5 9 12l5.5 5.5'});
else if(name==='chevron-right')add('path',{d:'M9.5 6.5 15 12l-5.5 5.5'});
else if(name==='check'){add('path',{d:'m6.5 12.5 3.5 3.5 7.5-8'});}
else if(name==='alert'){add('path',{d:'M12 4.5 20 19H4Z'});line(12,9,12,13);add('circle',{cx:12,cy:16.2,r:0.8,fill:'currentColor',stroke:'none'});}
else if(name==='panel'){add('rect',{x:4,y:5,width:16,height:14,rx:2});line(9,5,9,19);} 
else if(name==='text'){line(6,7,18,7);line(6,12,16,12);line(6,17,14,17);} 
else if(name==='heading'){line(6,6,6,18);line(13,6,13,18);line(6,12,13,12);line(16,8,19,8);line(17.5,8,17.5,18);} 
else if(name==='section'){add('rect',{x:4,y:5,width:16,height:14,rx:2});line(4,10,20,10);} 
else if(name==='row'){add('rect',{x:4,y:6,width:16,height:12,rx:2});line(12,6,12,18);} 
else if(name==='repeat'){add('path',{d:'M7 7h9l-2.5-2.5M17 17H8l2.5 2.5'});add('path',{d:'M17 7v4M7 17v-4'});} 
else if(name==='table'){add('rect',{x:4,y:5,width:16,height:14,rx:2});line(4,10,20,10);line(10,5,10,19);line(15,5,15,19);} 
else if(name==='chart'){line(5,19,5,5);line(5,19,20,19);add('rect',{x:8,y:12,width:2.8,height:7,rx:.6});add('rect',{x:13,y:8,width:2.8,height:11,rx:.6});add('rect',{x:18,y:5,width:2,height:14,rx:.6});} 
else if(name==='calculation'){add('path',{d:'M7 6h10M7 18h10M9 12h6'});add('circle',{cx:7,cy:12,r:.8,fill:'currentColor',stroke:'none'});add('circle',{cx:17,cy:12,r:.8,fill:'currentColor',stroke:'none'});} 
else if(name==='percentage'){add('circle',{cx:8,cy:8,r:2});add('circle',{cx:16,cy:16,r:2});line(7,17,17,7);} 
else if(name==='divider'){line(4,12,20,12);} 
else if(name==='spacer'){line(6,8,18,8);line(6,16,18,16);add('path',{d:'m12 10-2 2 2 2 2-2Z'});} 
else if(name==='pagebreak'){line(4,8,9,8);line(15,8,20,8);line(4,16,9,16);line(15,16,20,16);add('path',{d:'m10 10 2 2 2-2'});} 
else if(name==='toc'){line(8,7,19,7);line(8,12,19,12);line(8,17,19,17);add('circle',{cx:5,cy:7,r:.8,fill:'currentColor',stroke:'none'});add('circle',{cx:5,cy:12,r:.8,fill:'currentColor',stroke:'none'});add('circle',{cx:5,cy:17,r:.8,fill:'currentColor',stroke:'none'});} 
else if(name==='image'){add('rect',{x:4,y:5,width:16,height:14,rx:2});add('circle',{cx:9,cy:9,r:1.4});add('path',{d:'m6 17 4-4 3 3 2-2 3 3'});} 
else if(name==='library'){add('rect',{x:5,y:5,width:12,height:14,rx:1.5});add('path',{d:'M8 3h11v14'});} 
else if(name==='settings'){line(5,7,19,7);line(5,12,19,12);line(5,17,19,17);add('circle',{cx:10,cy:7,r:1.6,fill:'var(--surface)',stroke:'currentColor'});add('circle',{cx:15,cy:12,r:1.6,fill:'var(--surface)',stroke:'currentColor'});add('circle',{cx:9,cy:17,r:1.6,fill:'var(--surface)',stroke:'currentColor'});} 
else add('circle',{cx:12,cy:12,r:8});return svg;}
function setIconButton(btn,name,label){btn.replaceChildren(iconSvg(name));btn.setAttribute('aria-label',label);btn.title=label;}
function iconButton(name,labelText,fn,cls=''){const b=button('',fn);b.className=cls||'writer-icon-button';setIconButton(b,name,labelText);return b;}
function ribbonCommand(labelText,icon,fn,primary=false){const b=button('',fn);b.className='writer-ribbon-command'+(primary?' is-primary':'');const i=el('span','','writer-ribbon-command-icon'),t=el('span',labelText,'writer-ribbon-command-label');const map={'↶':'chevron-right','↷':'chevron-left','▣':'panel','◷':'info','◇':'panel','≡':'panel','◫':'panel','▤':'panel','↧':'chevron-down','▥':'panel','＋':'panel','▱':'panel','✓':'check','◉':'info'};if(map[icon])i.append(iconSvg(map[icon]));else i.textContent=icon;i.setAttribute('aria-hidden','true');b.append(i,t);b.setAttribute('aria-label',labelText);return b;}
function ribbonGroup(titleText,...controls){const g=el('section','','writer-ribbon-group'),body=el('div','','writer-ribbon-group-body');body.append(...controls.filter(Boolean));g.append(body,el('span',titleText,'writer-ribbon-group-title'));return g;}
function leftInsertButton(kind){const iconMap={paragraph:'text',heading:'heading',section:'section',row:'row',repeat:'repeat',table:'table',chart:'chart',calculation:'calculation',percentage:'percentage',divider:'divider',spacer:'spacer',pagebreak:'pagebreak',toc:'toc',image:'image'};const b=button('',()=>insert(kind));b.className='writer-insert-command';b.dataset.kind=kind;const mark=el('span','','writer-insert-command-icon');mark.append(iconSvg(iconMap[kind]||'panel'));b.append(mark,el('span',names[kind],'writer-insert-command-label'));return b;}
function propertySection(titleText,key,openDefault=true){const d=el('details','','writer-property-section'),summary=el('summary'),body=el('div','','writer-property-section-body'),stateKey=(active||'page')+':'+key;summary.append(el('span',titleText));d.append(summary,body);d.open=propertyOpenState.has(stateKey)?propertyOpenState.get(stateKey):openDefault;d.addEventListener('toggle',()=>propertyOpenState.set(stateKey,d.open));return {section:d,body};}
function tableColumnSection(titleText,key){const {section,body}=propertySection(titleText,key,false);section.classList.add('writer-table-column-section');return {section,body};}

function input(value,fn,type='text'){const n=el(type==='textarea'?'textarea':'input','','control');if(type!=='textarea')n.type=type;n.value=value??'';n.oninput=()=>fn(type==='number'?(n.value===''?null:Number(n.value)):n.value);return n;}
function choose(value,items,fn){const n=el('select','','control');for(const [v,t] of items){const o=el('option',t);o.value=v;n.append(o);}n.value=value??'';n.onchange=()=>fn(n.value);return n;}
function label(text,control){const l=el('label',text);control.setAttribute('aria-label',text);l.append(control);return l;}
function check(text,value,fn){const n=el('input');n.type='checkbox';n.checked=!!value;n.onchange=()=>fn(n.checked);const l=el('label');l.append(n,el('span',text));return l;}
function modal(title){const d=el('dialog','','writer-dialog');d.dir='rtl';const heading=el('div','','dialog-heading'),h=el('h2',title);h.id=uid();d.setAttribute('aria-labelledby',h.id);const close=button('×',()=>d.close());close.className='dialog-close';close.setAttribute('aria-label',scText('إغلاق ')+title);heading.append(h,close);d.append(heading);d.onclose=()=>d.remove();document.body.append(d);d.showModal();return d;}
function schema(){return catalog.find(s=>s.id===model?.schema_id);}
function renderLandingOverview(){if(!library||!library.drafts)return;dashboardTabs.replaceChildren();for(const [id,labelText] of [['templates',scText('القوالب')],['components',scText('المكونات')]]){const b=button(labelText,()=>{landingTab=id;renderLandingOverview();});if(id===landingTab)b.setAttribute('aria-current','page');dashboardTabs.append(b);}dashboardBody.replaceChildren();
if(landingTab==='templates'){const heading=el('div','','writer-dashboard-heading');heading.append(el('div'));heading.firstChild.append(el('h3',scText('قوالب التقارير')),el('p',scText('المخرجات وسجل الإنشاء موجودان في سجل التصدير الموحد أسفل صفحة التصدير.'),'writer-hint'));heading.append(el('span',(library.drafts||[]).length+scText(' قالب'),'writer-badge'));dashboardBody.append(heading);if(!library.drafts.length)dashboardBody.append(el('p',scText('لا توجد قوالب بعد. أنشئ تقريرًا جديدًا للبدء.'),'writer-empty'));for(const item of [...library.drafts].reverse()){const versions=(library.versions||[]).filter(v=>v.draft_id===item.id),latest=versions.sort((a,b)=>b.number-a.number)[0];const row=el('section','','writer-dashboard-row'),meta=el('div');meta.append(el('strong',item.template.title),el('p',(item.template.mode==='per_profile'?scText('تقرير لكل ملف'):scText('تقرير مجموعة'))+' · '+(latest?scText('نسخة جاهزة ')+latest.number:scText('مسودة فقط'))+' · '+item.updated_at,'writer-hint'));const deleteTemplateButton=button(scText('حذف القالب'),async()=>{if(!await requestConfirmation(scText('حذف القالب «')+item.template.title+scText('» ونسخه الجاهزة؟ لن تُحذف التقارير التي سبق إنشاؤها من سجل التصدير.'),{title:scText('حذف القالب'),confirmLabel:scText('حذف'),danger:true}))return;await call('delete_template',{id:item.id});if(saved?.id===item.id){saved=null;model=fresh();active=null;undo=[];redo=[];epoch++;render();}library=await call('list');renderLandingOverview();});deleteTemplateButton.className='button button-danger-quiet';deleteTemplateButton.dataset.actionKind='delete';row.append(meta,button(scText('فتح'),async()=>{if(model&&saved?.id!==item.id)await save();model=clone(item.template);saved=item;active=null;undo=[];redo=[];epoch++;render();await openEditor();}),button(scText('إنشاء'),async()=>{if(model&&saved?.id!==item.id)await save();model=clone(item.template);saved=item;active=null;render();await runDialog(false);}),deleteTemplateButton);dashboardBody.append(row);}}
else{const latest=new Map();for(const c of library.components||[])if(!latest.has(c.component_id)||latest.get(c.component_id).number<c.number)latest.set(c.component_id,c);dashboardBody.append(el('h3',scText('المكونات القابلة لإعادة الاستخدام')));if(!latest.size)dashboardBody.append(el('p',scText('لا توجد مكونات محفوظة بعد.'),'writer-empty'));for(const c of latest.values()){const row=el('section','','writer-dashboard-row'),meta=el('div');meta.append(el('strong',c.title),el('p',(c.kind||scText('مكوّن'))+scText(' · نسخة ')+c.number+' · '+(c.required_context||scText('بدون سياق')),'writer-hint'));row.append(meta);dashboardBody.append(row);}dashboardBody.append(button(scText('إدارة المكونات في المحرر'),async()=>{await openEditor();componentsDialog();}));}}
function reportHelp(){const d=modal(scText('كيف أنشئ تقريرًا؟'));const steps=el('ol','','writer-help-steps');for(const text of [scText('ابدأ من «تقرير جديد»: اختر ملخص مجموعة أو تقريرًا مستقلًا لكل ملف.'),scText('اضغط داخل النص واكتب. من شريط «إدراج داخل النص» أضف حقلًا أو حسابًا أو نسبة أو تاريخًا عند المؤشر.'),scText('اضغط على العنصر الأزرق لتغيير الحقل أو الحساب في الخصائص. الأرقام النهائية تظهر في المعاينة.'),scText('اضغط «معاينة»، ثم «التالي» لاختيار الملفات والمخرج ومراجعة PDF.'),scText('اضغط «إنشاء تقرير». اعتمد نسخة جاهزة عندما يطلبها التطبيق، ثم اختر الملفات واضغط «بدء الإنشاء» ونزّل النتيجة.')])steps.append(el('li',text));d.append(steps,el('p',scText('تقرير مجموعة: مستند واحد لجميع الملفات، مثل «عدد الملفات هو [حساب]». تقرير لكل ملف: قالب كامل يتكرر لكل شخص، ويمكن إدراج اسمه مباشرة.'),'writer-hint'));}
async function starterDialog(){await init();if(!model)return;if(!editor.open)editor.showModal();const d=modal(scText('تقرير جديد — اختر نقطة البداية'));let schemaId=model.schema_id,kind='summary';d.append(label(scText('التصميم المستخدم'),choose(schemaId,catalog.map(s=>[s.id,displaySchemaName(s)]),v=>{schemaId=v;})),label(scText('نوع البداية'),choose(kind,[['summary',scText('ملخص المجموعة — عدد الملفات وجدول')],['profile',scText('تقرير لكل ملف — حقول داخل النص')],['blank',scText('مستند فارغ')]],v=>{kind=v;})),el('p',scText('ستُحفظ المسودة الحالية قبل إنشاء مستند جديد. البيانات الفعلية تظهر عند المعاينة.'),'writer-hint'),button(scText('إنشاء المستند والبدء'),async()=>{await save();const t=fresh();t.schema_id=schemaId;t.mode=kind==='profile'?'per_profile':'collection';const fs=(catalog.find(s=>s.id===schemaId)?.fields||[]).filter(f=>!f.repeated&&!['spacer','field_group'].includes(f.type)&&f.type!=='file').slice(0,3);const fieldToken=f=>({type:'field',ref:{schema:schemaId,category:f.category_id,field:f.id,context:'profile'},empty:'—'});const paragraph=content=>({id:uid(),type:'paragraph',content});t.title=kind==='profile'?scText('تقرير الملف'):kind==='summary'?scText('ملخص الملفات'):scText('تقرير جديد');t.blocks=[{id:uid(),type:'heading',level:1,content:[{type:'text',text:t.title}]}];if(kind==='profile'){for(const f of fs)t.blocks.push(paragraph([{type:'text',text:displayLabel(f).split(' / ').at(-1)+': '},fieldToken(f)]));if(!fs.length)t.blocks.push(paragraph([{type:'text',text:scText('اكتب تقرير الملف هنا.')}]));}else if(kind==='summary'){t.blocks.push(paragraph([{type:'text',text:scText('يضم هذا التقرير ')},{type:'calculation',calculation:{kind:'aggregate',source:{kind:'profiles'},op:'count'}},{type:'text',text:scText(' ملفًا.')}]));if(fs.length)t.blocks.push({id:uid(),type:'table',source:{kind:'profiles'},columns:fs.map(f=>({label:displayLabel(f).split(' / ').at(-1),ref:fieldToken(f).ref,width:1}))});}else t.blocks.push(paragraph([{type:'text',text:''}]));model=t;saved=null;undo=[];redo=[];zone='blocks';active=t.blocks[1].id;tokenIndex=null;selectionRange=null;changed(true);await save();d.close();fitPages();document.getElementById('writer-'+active)?.querySelector('.writer-edit')?.focus();}));}
function inlineAction(kind){if(!find()?.b?.content){insert('paragraph');const b=find().b;b.content=[{type:'text',text:''}];renderStage();}if(kind==='field'){renderProperties();const search=right.querySelector('input[type=search]');search?.focus();search?.scrollIntoView({block:'nearest'});message(scText('اختر حقلًا من الخصائص لإدراجه داخل النص.'));return;}if(kind==='parameter'){if(!model.parameters.length){message(scText('أضف معاملًا أولًا من «المعاملات».'));parametersDialog();return;}const d=modal(scText('إدراج معامل داخل النص'));for(const p of model.parameters)d.append(button(displayLabel(p),()=>{insertToken({type:'parameter',id:p.id});d.close();}));return;}const tokens={calculation:{type:'calculation',calculation:{kind:'aggregate',source:{kind:'profiles'},op:'count'}},percentage:{type:'calculation',calculation:{kind:'percentage',left:{kind:'literal',value:0},right:{kind:'literal',value:100}},decimals:2,suffix:'%'},date:{type:'system',name:'date'},join:{type:'join',source:{kind:'current_cards'},separator:'، '}};insertToken(tokens[kind]);}
function fields(){return (schema()?.fields||[]).filter(f=>!['spacer','field_group'].includes(f.type));}
function ref(f,context){return {schema:model.schema_id,category:f.category_id,field:f.id,context:context||(f.repeated?'card':'profile')};}
function newBlock(type){const b={id:uid(),type};if(['paragraph','heading','section'].includes(type))b.content=[{type:'text',text:type==='paragraph'?scText('اكتب هنا…'):scText('عنوان جديد')}];if(type==='heading'||type==='section')b.level=1;if(type==='section'||type==='repeat')b.children=[];if(type==='row')b.cells=[{weight:1,children:[]},{weight:1,children:[]}];if(['repeat','table','chart'].includes(type))b.source={kind:'profiles'};if(type==='table')b.columns=[];if(type==='chart'){b.chart='bar';b.measure={op:'count'};}if(type==='calculation'||type==='percentage')b.calculation={kind:'aggregate',source:{kind:'profiles'},op:'count'};return b;}
function fresh(){const defaults=library.settings?.[0]?.settings||{};return {format:'schemacraft-document',version:3,locale:window.SchemaCraftI18n?.language||'ar',title:scText('تقرير جديد'),schema_id:catalog[0]?.id||'',mode:'collection',page:{margin:defaults.margin||18,font_size:defaults.font_size||11,direction:'rtl',size:defaults.page_size||'A4',orientation:defaults.orientation||'portrait',first_header_mode:'same',first_footer_mode:'same',automatic_page_number:true},parameters:[],calculations:{},header:clone(defaults.header||[]),footer:clone(defaults.footer||[]),first_header:[],first_footer:[],blocks:[{...newBlock('heading'),content:[{type:'text',text:scText('عنوان التقرير')}]},newBlock('paragraph')]};}
function walk(list,fn,parent=null){for(const b of list){fn(b,list,parent);if(b.children)walk(b.children,fn,b);for(const c of b.cells||[])walk(c.children,fn,b);}}
function find(id=active){let item;for(const z of ['blocks','header','footer','first_header','first_footer'])walk(model?.[z]||[],(b,list,parent)=>{if(b.id===id)item={b,list,parent};});return item;}
function remember(){undo.push(clone(model));if(undo.length>50)undo.shift();redo=[];}
function changed(redraw=false){right.querySelectorAll('.writer-calculation-description').forEach(n=>{if(n._calculation)n.textContent=describeCalc(n._calculation);});epoch++;message(scText('تغييرات قيد الحفظ…'));clearTimeout(timer);timer=setTimeout(()=>save().catch(e=>message(scText('لم تُحفظ المسودة: ')+e.message,true)),800);clearTimeout(validationTimer);validationTimer=setTimeout(validate,500);if(redraw)render();}
function mutate(fn,redraw=true){remember();fn();changed(redraw);}
async function save(){clearTimeout(timer);timer=null;const snapshot=clone(model),generation=epoch;saveQueue=saveQueue.catch(()=>{}).then(async()=>{const r=await call('save',{template:snapshot,id:saved?.id,revision:saved?.revision});saved=r.saved;if(generation===epoch)message(scText('المسودة محفوظة تلقائيًا'));showProblems(r.problems);return saved;});return saveQueue;}
async function validate(){try{const generation=epoch,r=await call('validate',{template:model});if(generation===epoch)showProblems(r.problems);}catch(e){message(e.message,true);}}
function showProblems(items=[]){const errorCount=items.filter(x=>x.severity==='error').length,warningCount=items.length-errorCount;problems.classList.toggle('is-clean',!items.length);problems.classList.toggle('has-errors',!!errorCount);if(!items.length)problems.open=false;else if(errorCount)problems.open=true;const summary=el('summary','','writer-problems-summary'),identity=el('div','','writer-problems-identity'),icon=el('span','','writer-problems-icon');icon.append(iconSvg(errorCount?'alert':'check'));identity.append(icon,el('span',items.length?scText('فحص المستند'):scText('المستند جاهز'),'writer-problems-title'));const counts=el('div','','writer-problems-counts');if(errorCount)counts.append(el('span',errorCount+scText(' خطأ'),'writer-problem-count is-error'));if(warningCount)counts.append(el('span',warningCount+scText(' تنبيه'),'writer-problem-count is-warning'));if(!items.length)counts.append(el('span',scText('لا توجد مشكلات'),'writer-problem-count is-ok'));summary.append(identity,counts);problems.replaceChildren(summary);if(items.length){const list=el('div','','writer-problem-list');for(const p of items){const b=button('',()=>{active=p.element;tokenIndex=null;render();document.getElementById('writer-'+active)?.scrollIntoView({block:'center'});});b.className='writer-problem-item '+(p.severity==='error'?'error':'warning');b.append(el('span',p.severity==='error'?scText('خطأ'):scText('تنبيه'),'writer-problem-severity'),el('span',p.message,'writer-problem-message'));list.append(b);}problems.append(list);}}
function currentTitle(b){if(['calculation','percentage'].includes(b.type))return describeCalc(b.calculation);return b.content?.map(t=>t.text||'◈').join('').slice(0,35)||names[b.type];}
function render(){if(!model)return;renderTop();renderLeft();renderStage();renderProperties();}
function renderTop(){
top.replaceChildren();
const title=input(model.title,v=>{model.title=v;changed();});title.classList.add('writer-document-title');title.setAttribute('aria-label',scText('اسم التقرير'));
const schemaSelect=choose(model.schema_id,catalog.map(s=>[s.id,displaySchemaName(s)]),v=>mutate(()=>{model.schema_id=v;}));schemaSelect.setAttribute('aria-label',scText('التصميم'));
const modeSelect=choose(model.mode,[['collection',scText('تقرير مجموعة')],['per_profile',scText('تقرير لكل ملف')]],v=>mutate(()=>{model.mode=v;}));modeSelect.setAttribute('aria-label',scText('وضع التقرير'));
const identity=el('div','','writer-document-identity');identity.append(title,el('div','','writer-document-meta'));identity.lastChild.append(schemaSelect,modeSelect);
top.append(identity,status);

const zones=[['blocks',scText('متن المستند')],['header',scText('رأس الصفحة المتكرر')],['footer',scText('تذييل الصفحة المتكرر')]];if(model.page.first_header_mode==='different')zones.push(['first_header',scText('رأس الصفحة الأولى')]);if(model.page.first_footer_mode==='different')zones.push(['first_footer',scText('تذييل الصفحة الأولى')]);if(!zones.some(x=>x[0]===zone))zone='blocks';
const ribbonTabs=el('nav','','writer-ribbon-tabs'),ribbonPanel=el('div','','writer-ribbon-panel');
for(const [id,labelText] of [['home',scText('الرئيسية')],['insert',scText('إدراج')],['layout',scText('تخطيط')],['report',scText('تقرير')]]){const tab=button(labelText,()=>{ribbonTab=id;renderTop();});tab.className='writer-ribbon-tab';if(ribbonTab===id)tab.setAttribute('aria-current','page');ribbonTabs.append(tab);}
const b=find()?.b;
if(ribbonTab==='home'){
 const undoBtn=ribbonCommand(scText('تراجع'),'↶',()=>{if(undo.length){redo.push(clone(model));model=undo.pop();changed(true);}}),redoBtn=ribbonCommand(scText('إعادة'),'↷',()=>{if(redo.length){undo.push(clone(model));model=redo.pop();changed(true);}});
 const zoneSelect=choose(zone,zones,v=>{zone=v;active=null;render();});zoneSelect.classList.add('writer-ribbon-select');
 ribbonPanel.append(ribbonGroup(scText('تحرير'),undoBtn,redoBtn),ribbonGroup(scText('نطاق المستند'),zoneSelect));
 if(b?.content){const styleSelect=choose(['heading','section'].includes(b.type)?'h'+(b.level||1):'paragraph',[['paragraph',scText('نص عادي')],['h1',scText('عنوان 1')],['h2',scText('عنوان 2')],['h3',scText('عنوان 3')]],v=>mutate(()=>{if(b.type==='section'){b.level=Number(v.slice(1))||1;return;}b.type=v==='paragraph'?'paragraph':'heading';b.level=Number(v.slice(1))||1;}));const alignSelect=choose(b.align||'right',[['right',scText('يمين')],['center',scText('توسيط')],['left',scText('يسار')]],v=>mutate(()=>{b.align=v;}));ribbonPanel.append(ribbonGroup(scText('تنسيق'),ribbonCommand(scText('عريض'),'B',()=>mutate(()=>{b.bold=!b.bold;})),ribbonCommand(scText('مائل'),'I',()=>mutate(()=>{b.italic=!b.italic;})),styleSelect,alignSelect));}
}
if(ribbonTab==='insert')ribbonPanel.append(ribbonGroup(scText('قيم داخل النص'),ribbonCommand(scText('إدراج حقل'),'▣',()=>inlineAction('field')),ribbonCommand(scText('حساب داخل النص'),'Σ',()=>inlineAction('calculation')),ribbonCommand(scText('نسبة داخل النص'),'%',()=>inlineAction('percentage')),ribbonCommand(scText('تاريخ'),'◷',()=>inlineAction('date')),ribbonCommand(scText('معامل'),'◇',()=>inlineAction('parameter'))),ribbonGroup(scText('أدوات البيانات'),ribbonCommand(scText('المعاملات'),'≡',parametersDialog),ribbonCommand(scText('المكونات'),'◫',componentsDialog)));
if(ribbonTab==='layout')ribbonPanel.append(ribbonGroup(scText('إعداد الصفحة'),ribbonCommand(scText('إعداد الصفحة'),'▤',()=>{active=null;renderProperties();}),choose(zone,zones,v=>{zone=v;active=null;render();})),ribbonGroup(scText('بنية المستند'),ribbonCommand(scText('فاصل صفحة'),'↧',()=>insert('pagebreak')),ribbonCommand(scText('صف تخطيط'),'▥',()=>insert('row')),ribbonCommand(scText('قسم'),'§',()=>insert('section'))));
if(ribbonTab==='report')ribbonPanel.append(ribbonGroup(scText('القالب والنسخ'),ribbonCommand(scText('تقرير جديد'),'＋',starterDialog),ribbonCommand(scText('ملف / نسخ'),'▱',libraryDialog),ribbonCommand(scText('حفظ نسخة جاهزة'),'✓',async()=>{await save();const r=await call('publish',{id:saved.id,revision:saved.revision});message(scText('النسخة ')+r.version.number+scText(' جاهزة'));})),ribbonGroup(scText('المعاينة والتصدير'),ribbonCommand(scText('معاينة'),'◉',()=>runDialog(true)),ribbonCommand(scText('إنشاء تقرير'),'PDF',()=>runDialog(false),true)));
const ribbonCollapse=iconButton(ribbonCollapsed?'chevron-down':'chevron-up',ribbonCollapsed?scText('إظهار الشريط'):scText('طي الشريط إلى أعلى'),()=>{ribbonCollapsed=!ribbonCollapsed;renderTop();requestAnimationFrame(fitPages);},'writer-ribbon-collapse');ribbonTabs.append(ribbonCollapse);format.classList.toggle('is-collapsed',ribbonCollapsed);ribbonPanel.hidden=ribbonCollapsed;format.replaceChildren(ribbonTabs,ribbonPanel);
}
function insert(type){mutate(()=>{const b=newBlock(type),target=find();let list=model[zone];if(target?.b.children)list=target.b.children;else if(target?.b.cells)list=target.b.cells[0].children;else if(target)list=target.list;const at=target&&list===target.list?list.indexOf(target.b)+1:list.length;list.splice(at,0,b);active=b.id;tokenIndex=null;});}
function renderLeft(){left.classList.toggle('is-collapsed',leftCollapsed);layout.classList.toggle('is-left-collapsed',leftCollapsed);left.replaceChildren();if(leftCollapsed){const reopen=iconButton('chevron-right',scText('فتح لوحة الإدراج والمخطط'),()=>{leftCollapsed=false;renderLeft();fitPages();},'writer-sidebar-collapse writer-sidebar-reopen');left.append(reopen);return;}const head=el('div','','writer-sidebar-heading'),headText=el('div');headText.append(el('strong',scText('المستند')),el('small',zone==='blocks'?scText('متن المستند'):zone.includes('header')?scText('رأس الصفحة'):scText('تذييل الصفحة'),'writer-sidebar-subtitle'));head.append(headText,iconButton('chevron-left',scText('طي اللوحة إلى اليسار'),()=>{leftCollapsed=true;renderLeft();fitPages();},'writer-sidebar-collapse'));left.append(head);
const insertSection=el('section','','writer-left-panel-section');insertSection.append(el('div',scText('إدراج'),'writer-left-section-title'));const groups=[[scText('النص والهيكل'),['paragraph','heading','section','row']],[scText('البيانات'),['repeat','table','chart','calculation','percentage']],[scText('الصفحة'),['divider','spacer','pagebreak','toc','image']]];for(const [groupTitle,kinds] of groups){const group=el('div','','writer-palette-group');group.append(el('small',groupTitle,'writer-palette-group-title'));const palette=el('div','','writer-palette');for(const kind of kinds)palette.append(leftInsertButton(kind));group.append(palette);insertSection.append(group);}left.append(insertSection);
const outlineSection=el('section','','writer-left-panel-section writer-outline-section');const outlineTitle=el('div','','writer-left-section-header');outlineTitle.append(el('span',scText('مخطط المستند'),'writer-left-section-title'),el('span',String((model[zone]||[]).length),'writer-mini-badge'));outlineSection.append(outlineTitle);const outline=el('div','','writer-outline');walk(model[zone],(b,list,parent)=>{const n=button('',()=>{active=b.id;tokenIndex=null;render();document.getElementById('writer-'+active)?.scrollIntoView({block:'center'});});n.dataset.blockId=b.id;if(parent)n.classList.add('is-nested');if(active===b.id)n.classList.add('selected');const text=el('span',currentTitle(b),'writer-outline-label'),type=el('small',names[b.type],'writer-outline-type');n.append(text,type);outline.append(n);});if(!outline.childElementCount)outline.append(el('p',scText('لا توجد عناصر بعد.'),'writer-empty-mini'));outlineSection.append(outline);left.append(outlineSection);
const reuse=el('section','','writer-left-panel-section writer-reuse-section');reuse.append(el('div',scText('إعادة الاستخدام'),'writer-left-section-title'));const actions=el('div','','writer-left-actions');const libraryButton=button('',componentsDialog);libraryButton.className='writer-left-action';const libraryIcon=el('span','','writer-left-action-icon');libraryIcon.append(iconSvg('library'));libraryButton.append(libraryIcon,el('span',scText('مكتبة المكونات')));const settingsButton=button('',settingsDialog);settingsButton.className='writer-left-action';const settingsIcon=el('span','','writer-left-action-icon');settingsIcon.append(iconSvg('settings'));settingsButton.append(settingsIcon,el('span',scText('الإعدادات العامة')));actions.append(libraryButton,settingsButton);reuse.append(actions);left.append(reuse);}
function tokenName(t){if(t.type==='field')return displayLabel(fields().find(f=>f.id===t.ref.field)).split(' / ').at(-1)||scText('حقل محذوف');if(t.type==='parameter')return displayLabel(model.parameters.find(p=>p.id===t.id))||scText('معامل محذوف');if(t.type==='system')return {date:scText('التاريخ'),profile_id:scText('رقم الملف'),index:scText('رقم العنصر'),total:scText('عدد العناصر'),first:scText('العنصر الأول'),last:scText('العنصر الأخير'),current_page:scText('رقم الصفحة'),total_pages:scText('عدد الصفحات')}[t.name];if(t.type==='join')return scText('قيم متكررة');if(t.type==='calculation')return describeCalc(t.calculation);return scText('عنصر');}
function editable(b){const n=el('div','','writer-edit');n.contentEditable='true';n.setAttribute('role','textbox');n.setAttribute('aria-label',names[b.type]);n.style.textAlign=b.align||'right';if(b.bold)n.style.fontWeight='bold';if(b.italic)n.style.fontStyle='italic';if(b.type==='heading'||b.type==='section'){n.style.fontSize=({1:22,2:17,3:14})[b.level||1]+'pt';n.style.fontWeight='bold';}
for(const [i,t] of (b.content||[]).entries()){if(t.type==='text')n.append(document.createTextNode(t.text));else{const span=el('span',tokenName(t),'writer-token');span.contentEditable='false';span.tabIndex=0;span.setAttribute('role','button');span.setAttribute('aria-label',scText('تعديل ')+tokenName(t));span.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();span.click();}};span.dataset.token=JSON.stringify(t);span.onclick=e=>{e.stopPropagation();active=b.id;const ordinal=[...n.querySelectorAll('.writer-token')].indexOf(span);tokenIndex=b.content.map((t,index)=>({t,index})).filter(x=>x.t.type!=='text')[ordinal]?.index??null;renderProperties();};n.append(span);}}
n.onfocus=()=>{if(active!==b.id){active=b.id;tokenIndex=null;renderProperties();renderTop();}};
n.oninput=()=>{const tokens=[];function read(parent){for(const child of parent.childNodes){if(child.nodeType===3)tokens.push({type:'text',text:child.textContent});else if(child.dataset?.token)tokens.push(JSON.parse(child.dataset.token));else if(child.nodeName==='BR')tokens.push({type:'text',text:'\n'});else{read(child);if(child.nodeName==='DIV')tokens.push({type:'text',text:'\n'});}}}read(n);b.content=tokens;changed();};
n.onbeforeinput=()=>{if(!undo.length||JSON.stringify(undo.at(-1))!==JSON.stringify(model))remember();};
n.onpaste=e=>{e.preventDefault();const text=e.clipboardData.getData('text/plain'),s=window.getSelection();if(s.rangeCount){const r=s.getRangeAt(0);r.deleteContents();const tn=document.createTextNode(text);r.insertNode(tn);r.setStartAfter(tn);r.collapse(true);s.removeAllRanges();s.addRange(r);n.dispatchEvent(new Event('input'));}};
const capture=()=>{const s=window.getSelection();if(s.rangeCount&&n.contains(s.anchorNode))selectionRange=s.getRangeAt(0).cloneRange();};n.onkeyup=capture;n.onmouseup=capture;return n;}
function blockView(b){const wrap=el('article','','writer-block'+(active===b.id?' active':''));wrap.id='writer-'+b.id;wrap.onclick=e=>{if(e.target.closest('.writer-edit,.writer-token,button'))return;e.stopPropagation();active=b.id;tokenIndex=null;renderProperties();renderTop();stage.querySelectorAll('.active').forEach(n=>n.classList.remove('active'));wrap.classList.add('active');};
if(b.type==='component')wrap.append(el('div',scText('مكوّن مرتبط · ')+(b.title||'')+' · '+(b.version==='latest'?scText('أحدث نسخة جاهزة'):scText('نسخة مثبتة')),'writer-placeholder'));
if(b.content)wrap.append(editable(b));
if(b.type==='divider')wrap.append(el('hr'));if(b.type==='spacer')wrap.style.height=(b.height||18)+'px';if(b.type==='toc')wrap.append(el('div',scText('المحتويات · تُحسب أرقام الصفحات من PDF النهائي'),'writer-placeholder'));
if(b.type==='image'){if(b.data){const im=el('img');im.src=b.data;im.style.width=(b.width||150)+'px';im.style.maxWidth='100%';wrap.append(im);}else wrap.append(el('div',scText('اختر صورة محلية من الخصائص'),'writer-placeholder'));}
if(b.type==='section'||b.type==='repeat'){const box=el('div','','writer-container');if(b.type==='repeat')box.append(el('div',b.source.kind==='profiles'?scText('لكل ملف مطابق'):scText('لكل بطاقة مطابقة'),'writer-container-caption'));for(const child of b.children)box.append(blockView(child));box.append(button(scText('+ فقرة داخلية'),()=>{active=b.id;insert('paragraph');}));wrap.append(box);}
if(b.type==='row'){const row=el('div','','writer-row');for(const cell of b.cells){const c=el('div','','writer-cell');c.style.flex=cell.weight;for(const child of cell.children)c.append(blockView(child));c.append(button('+',()=>mutate(()=>{const child=newBlock('paragraph');cell.children.push(child);active=child.id;})));row.append(c);}wrap.append(row);}
if(b.type==='table'){const t=el('table','','writer-preview-table'),tr=el('tr');for(const c of b.columns)tr.append(el('th',displayLabel(c)+(c.calculation&&c.show_description?' — '+describeCalc(c.calculation):'')));t.append(tr);const row=el('tr');for(const c of b.columns)row.append(el('td',c.row_number?'1':scText('◈ قيمة حية')));t.append(row);wrap.append(t,el('small',scText('جدول حي · تُعرض البيانات الفعلية في المعاينة'),'writer-hint'));}
if(b.type==='chart')wrap.append(el('div',names[b.type]+scText(' · يرتبط مباشرة ببيانات التقرير'),'writer-placeholder'));if(['calculation','percentage'].includes(b.type))wrap.append(el('div',describeCalc(b.calculation),'writer-calculation-description'));return wrap;}
function renderStage(){stage.replaceChildren();let pages=[[]];for(const b of model[zone]||[]){if(b.type==='pagebreak'){pages.push([]);continue;}pages.at(-1).push(b);}const [pw,ph]=pageMm();for(const [i,blocks] of pages.entries()){const page=el('section','','writer-page');page.style.width=pw+'mm';page.style.minHeight=ph+'mm';page.style.fontSize=model.page.font_size+'pt';page.style.padding=(model.page.margin||18)+'mm';if(zone==='blocks'){const hm=i===0?model.page.first_header_mode||'same':'same',header=hm==='none'?[]:hm==='different'?(model.first_header||[]):model.header;if(header.length){const h=el('div','','writer-chrome');for(const b of header)h.append(blockView(b));page.append(h);}}for(const b of blocks)page.append(blockView(b));if(zone==='blocks'){const fm=i===0?model.page.first_footer_mode||'same':'same',footer=fm==='none'?[]:fm==='different'?(model.first_footer||[]):model.footer;if(footer.length){const f=el('div','','writer-chrome footer');for(const b of footer)f.append(blockView(b));page.append(f);}}page.append(el('div',(model.page.size||'A4')+' · '+(model.page.orientation==='landscape'?scText('أفقي'):scText('عمودي'))+' · '+(i+1)+scText(' · التدفق النهائي في معاينة PDF'),'writer-page-label'));stage.append(page);}fitPages();}
function insertToken(token){const b=find()?.b;if(!b?.content){message(scText('حدد موضعًا داخل فقرة أو عنوان أولًا.'),true);return;}remember();token={...token,token_id:uid()};const editableNode=document.getElementById('writer-'+b.id)?.querySelector('.writer-edit');if(selectionRange&&editableNode?.contains(selectionRange.startContainer)&&editableNode.contains(selectionRange.endContainer)&&!selectionRange.startContainer.parentElement?.closest('.writer-token')){const span=el('span',tokenName(token),'writer-token');span.contentEditable='false';span.dataset.token=JSON.stringify(token);selectionRange.deleteContents();selectionRange.insertNode(span);selectionRange.setStartAfter(span);selectionRange.collapse(true);editableNode.dispatchEvent(new Event('input'));}else{b.content.push(token);changed();}tokenIndex=b.content.findIndex(t=>t.token_id===token.token_id);selectionRange=null;renderStage();renderProperties();renderTop();right.querySelector('#writer-token-properties')?.scrollIntoView({block:'start'});message(scText('أُدرج العنصر داخل النص. اضغط عليه لتعديل إعداداته؛ تظهر قيمته في المعاينة.'));}
function fieldPicker(value,fn,filter=()=>true){return choose(value?.field||'',[['',scText('اختر حقلًا')],...fields().filter(filter).map(f=>[f.id,displayLabel(f)])],id=>{const f=fields().find(f=>f.id===id);if(f)fn(ref(f));});}
function sourceEditor(owner,box){box.append(label(scText('مصدر المحتوى'),choose(owner.source?.kind||'profiles',[['profiles',scText('الملفات')],['cards',scText('بطاقات من كل الملفات')],['current_cards',scText('بطاقات الملف الحالي')],['current_profile',scText('الملف الحالي فقط')],['current_card',scText('البطاقة الحالية فقط')],['current_row',scText('الصف الحالي')],['current_group',scText('المجموعة الحالية')]],v=>mutate(()=>{owner.source={kind:v};}))));if(['cards','current_cards'].includes(owner.source?.kind))box.append(label(scText('فئة البطاقات'),choose(owner.source?.category||'',[['',scText('اختر الفئة')],...(schema()?.categories||[]).filter(c=>c.kind!=='main').map(c=>[c.id,displayLabel(c)])],v=>mutate(()=>{owner.source.category=v;}))));}
function filterEditor(owner,box,key='filter'){const details=el('details');details.open=true;details.append(el('summary',key==='when'?scText('شرط الظهور'):scText('مرشح البيانات')));const tree=el('div');details.append(tree);box.append(details);
function draw(c,parent,remove){const wrap=el('div','','writer-filter');parent.append(wrap);if(!c){wrap.append(button(scText('إضافة شروط'),()=>mutate(()=>{owner[key]={kind:'all',items:[]};})));return;}if(['all','any'].includes(c.kind)){wrap.append(choose(c.kind,[['all',scText('كل الشروط (AND)')],['any',scText('أي شرط (OR)')]],v=>mutate(()=>{c.kind=v;})));for(const child of c.items)draw(child,wrap,()=>c.items.splice(c.items.indexOf(child),1));wrap.append(button(scText('+ شرط'),()=>mutate(()=>c.items.push({kind:'rule',op:'eq',value:''}))),button(scText('+ مجموعة'),()=>mutate(()=>c.items.push({kind:'all',items:[]}))),button(scText('+ توجد بطاقة'),()=>mutate(()=>c.items.push({kind:'exists',where:{kind:'all',items:[]}}))));}else if(c.kind==='exists'){wrap.append(el('small',scText('الملف لديه بطاقة واحدة تحقق كل الشروط')),choose(c.category||'',[['',scText('فئة البطاقات')],...(schema()?.categories||[]).filter(x=>x.kind!=='main').map(x=>[x.id,displayLabel(x)])],v=>mutate(()=>{c.category=v;})));draw(c.where,wrap,()=>{});}else{wrap.append(fieldPicker(c.ref,r=>mutate(()=>{c.ref=r;c.value='';})));const f=fields().find(f=>f.id===c.ref?.field),ops=[['eq',scText('يساوي')],['ne',scText('لا يساوي')],['empty',scText('فارغ')],['not_empty',scText('غير فارغ')]];if((f?.type==='number'&&f?.number_behavior?.storage_mode!=='text')||f?.type?.startsWith('date_'))ops.push(['gt',scText('أكبر من')],['gte',scText('أكبر أو يساوي')],['lt',scText('أصغر من')],['lte',scText('أصغر أو يساوي')]);if(['text','textarea'].includes(f?.type)||(f?.type==='number'&&f?.number_behavior?.storage_mode==='text'))ops.push(['contains',scText('يحتوي')]);if(f?.type==='checkbox_group')ops.push(['includes',scText('يتضمن')]);wrap.append(choose(c.op,ops,v=>mutate(()=>{c.op=v;})));if(!['empty','not_empty'].includes(c.op)){wrap.append(choose(typeof c.value==='object'?'parameter':'value',[['value',scText('قيمة ثابتة')],['parameter',scText('معامل تشغيل')]],v=>mutate(()=>{c.value=v==='parameter'?{parameter:model.parameters[0]?.id}:'';})));if(typeof c.value==='object')wrap.append(choose(c.value.parameter,model.parameters.map(p=>[p.id,displayLabel(p)]),v=>mutate(()=>{c.value={parameter:v};})));else if(f?.type==='checkbox')wrap.append(choose(String(c.value),[['true','نعم'],['false','لا']],v=>mutate(()=>{c.value=v==='true';})));else if(['select','yes_no','checkbox_group'].includes(f?.type))wrap.append(choose(c.value,[['',scText('اختر قيمة')],...(f.options||[]).map(o=>[o.id,displayLabel(o)])],v=>mutate(()=>{c.value=v;})));else wrap.append(input(c.value,v=>{c.value=v;changed();},f?.type==='number'&&f?.number_behavior?.storage_mode!=='text'?'number':'text'));}}if(remove)wrap.append(button(scText('حذف الشرط'),()=>mutate(remove)));}
draw(owner[key],tree,()=>{delete owner[key];});}
function describeCalc(calc){return window.SchemaCraftFormula.describe(calc,schema()||{},model||{});}
function descriptionOption(owner,box){const control=check(scText('إظهار شرح الحساب في التقرير النهائي'),owner.show_description===true,v=>mutate(()=>{owner.show_description=v;if(v)model.locale=window.SchemaCraftI18n?.language||'ar';}));control.classList.add('writer-description-option');box.append(control);}
function calculationEditor(calc,box){const explanation=el('p',describeCalc(calc),'writer-calculation-description');explanation._calculation=calc;box.append(explanation);box.append(label(scText('الحساب'),choose(calc.kind,[['aggregate',scText('عدد / مجموع / متوسط القيم')],['percentage',scText('نسبة مئوية')],['ratio',scText('نسبة')],['add',scText('جمع')],['subtract',scText('طرح')],['multiply',scText('ضرب')],['literal',scText('رقم ثابت')],['parameter',scText('معامل رقمي')],['age',scText('العمر')],['days',scText('فرق الأيام')],['ref',scText('حساب قابل لإعادة الاستخدام')]],v=>mutate(()=>{for(const k of Object.keys(calc))delete calc[k];Object.assign(calc,{kind:v,...(v==='aggregate'?{source:{kind:'profiles'},op:'count'}:v==='literal'?{value:0}:['percentage','ratio','add','subtract','multiply'].includes(v)?{left:{kind:'literal',value:0},right:{kind:'literal',value:100}}:{})});}))));if(calc.kind==='ref')box.append(choose(calc.id,[['',scText('اختر الحساب')],...Object.keys(model.calculations).map(id=>[id,model.calculations[id].title||id])],v=>mutate(()=>{calc.id=v;})));else if(calc.kind==='literal')box.append(label(scText('القيمة الرقمية'),input(calc.value,v=>{calc.value=v;changed();},'number')));else if(calc.kind==='parameter')box.append(choose(calc.id,model.parameters.filter(p=>p.type==='number').map(p=>[p.id,displayLabel(p)]),v=>mutate(()=>{calc.id=v;})));else if(['age','days'].includes(calc.kind))box.append(fieldPicker(calc.ref,r=>mutate(()=>{calc.ref=r;}),f=>f.type==='date_gregorian'));else if(calc.kind==='aggregate'){sourceEditor(calc,box);box.append(choose(calc.op,reducers(),v=>mutate(()=>{calc.op=v;})));if(!['count','profile_count'].includes(calc.op))box.append(fieldPicker(calc.ref,r=>mutate(()=>{calc.ref=r;})));filterEditor(calc,box);}else if(calc.left){const a=el('details'),b=el('details');a.open=true;b.open=true;a.append(el('summary',calc.kind==='percentage'||calc.kind==='ratio'?scText('البسط'):scText('القيمة الأولى')));b.append(el('summary',calc.kind==='percentage'||calc.kind==='ratio'?scText('المقام'):scText('القيمة الثانية')));calculationEditor(calc.left,a);calculationEditor(calc.right,b);box.append(a,b);}}
function reducers(){return [['count',scText('عدد الصفوف')],['profile_count',scText('عدد الملفات المميزة')],['nonempty',scText('عدد القيم غير الفارغة')],['distinct',scText('عدد القيم المميزة')],['sum',scText('المجموع')],['average',scText('المتوسط')],['min',scText('الأدنى')],['max',scText('الأعلى')],['median',scText('الوسيط')]];}
function renderProperties(){
const keepScroll=right.scrollTop;queueMicrotask(()=>{right.scrollTop=keepScroll;});stage.querySelectorAll('.writer-block').forEach(n=>n.classList.toggle('active',n.id==='writer-'+active));left.querySelectorAll('[data-block-id]').forEach(n=>{n.classList.toggle('selected',n.dataset.blockId===active);n.setAttribute('aria-pressed',String(n.dataset.blockId===active));});
right.classList.toggle('is-collapsed',rightCollapsed);layout.classList.toggle('is-right-collapsed',rightCollapsed);right.replaceChildren();if(rightCollapsed){right.append(iconButton('chevron-left',scText('فتح لوحة الخصائص'),()=>{rightCollapsed=false;renderProperties();fitPages();},'writer-sidebar-collapse writer-sidebar-reopen'));return;}const target=find(),b=target?.b;const heading=el('div','','writer-properties-heading'),headingText=el('div');headingText.append(el('h3',b?scText('خصائص ')+names[b.type]:scText('إعدادات الصفحة')),el('p',b?scText('عدّل العنصر المحدد. تبقى الأقسام المفتوحة كما هي أثناء التعديل.'):(model.page.size||'A4')+' · '+(model.page.orientation==='landscape'?scText('أفقي'):scText('عمودي'))+' · RTL','writer-hint'));const headingTools=el('div','','writer-properties-heading-tools');if(b)headingTools.append(el('span',names[b.type],'writer-badge'));headingTools.append(iconButton('chevron-right',scText('طي لوحة الخصائص إلى اليمين'),()=>{rightCollapsed=true;renderProperties();fitPages();},'writer-sidebar-collapse'));heading.append(headingText,headingTools);right.append(heading);
if(!b){const page=propertySection(scText('الصفحة والطباعة'),'page',true);page.body.append(label(scText('حجم الصفحة'),choose(model.page.size||'A4',[['A4','A4'],['A3','A3'],['Letter','Letter'],['Legal','Legal']],v=>mutate(()=>{model.page.size=v;}))),label(scText('اتجاه الصفحة'),choose(model.page.orientation||'portrait',[['portrait',scText('عمودي')],['landscape',scText('أفقي')]],v=>mutate(()=>{model.page.orientation=v;}))),label(scText('حجم النص'),input(model.page.font_size,v=>{model.page.font_size=v;changed(true);},'number')),label(scText('الهوامش (مم)'),input(model.page.margin,v=>{model.page.margin=v;changed(true);},'number')));right.append(page.section);const chrome=propertySection(scText('الرأس والتذييل'),'page-chrome',true);chrome.body.append(label(scText('رأس الصفحة الأولى'),choose(model.page.first_header_mode||'same',[['same',scText('مثل بقية الصفحات')],['different',scText('رأس مختلف')],['none',scText('بدون رأس')]],v=>mutate(()=>{model.page.first_header_mode=v;model.first_header||=[];}))),label(scText('تذييل الصفحة الأولى'),choose(model.page.first_footer_mode||'same',[['same',scText('مثل بقية الصفحات')],['different',scText('تذييل مختلف')],['none',scText('بدون تذييل')]],v=>mutate(()=>{model.page.first_footer_mode=v;model.first_footer||=[];}))),check(scText('إظهار رقم الصفحة تلقائيًا أسفل الصفحة'),model.page.automatic_page_number!==false,v=>mutate(()=>{model.page.automatic_page_number=v;})),el('p',scText('يمكن إدراج رقم الصفحة وعدد الصفحات داخل الرأس أو التذييل. المعاينة هي المرجع النهائي لتدفق الصفحات.'),'writer-hint'));right.append(chrome.section);return;}

const quick=el('div','','writer-property-actions');quick.append(button('↑',()=>mutate(()=>{const i=target.list.indexOf(b);if(i>0)target.list.splice(i-1,0,target.list.splice(i,1)[0]);})),button('↓',()=>mutate(()=>{const i=target.list.indexOf(b);if(i<target.list.length-1)target.list.splice(i+1,0,target.list.splice(i,1)[0]);})),button(scText('نسخ'),()=>mutate(()=>{const n=clone(b);walk([n],x=>x.id=uid());target.list.splice(target.list.indexOf(b)+1,0,n);active=n.id;})),button(scText('حذف'),()=>mutate(()=>{target.list.splice(target.list.indexOf(b),1);active=null;})));right.append(quick);

const position=propertySection(scText('الموضع والسياق'),'position',false);const descendants=new Set();walk([b],x=>descendants.add(x.id));const parents=[['',scText('متن المستند')]];walk(model.blocks,x=>{if(x.children&&!descendants.has(x.id))parents.push([x.id,currentTitle(x)]);});position.body.append(label(scText('نقل إلى'),choose(target.parent?.id||'',parents,id=>mutate(()=>{target.list.splice(target.list.indexOf(b),1);(id?find(id).b.children:model.blocks).push(b);}))),el('small',scText('نقل العنصر لا يغيّر سياق حقوله تلقائيًا.'),'writer-hint'));right.append(position.section);

if(tokenIndex!==null&&b.content?.[tokenIndex]){const t=b.content[tokenIndex],token=propertySection(scText('العنصر النصي المحدد'),'token',true);token.section.id='writer-token-properties';if(t.type==='field')token.body.append(label(scText('الحقل'),fieldPicker(t.ref,r=>mutate(()=>{t.ref=r;}))),label(scText('السياق'),choose(t.ref.context,[['profile',scText('الملف الحالي')],['card',scText('البطاقة الحالية')],['row',scText('صف الجدول')]],v=>mutate(()=>{t.ref.context=v;}))),label(scText('عند الفراغ'),input(t.empty||'',v=>{t.empty=v;changed();})),check(scText('قيمة مطلوبة'),t.required,v=>mutate(()=>{t.required=v;})),label(scText('المنازل العشرية'),input(t.decimals,v=>{if(v===null)delete t.decimals;else t.decimals=v;changed();},'number')));if(t.type==='calculation'){token.body.append(el('p',scText('عدّل الدالة والمصدر هنا، ثم افتح المعاينة لرؤية القيمة.'),'writer-hint'));calculationEditor(t.calculation,token.body);descriptionOption(t,token.body);token.body.append(label(scText('المنازل العشرية'),input(t.decimals,v=>{if(v===null)delete t.decimals;else t.decimals=v;changed();},'number')),label(scText('لاحقة النتيجة'),input(t.suffix||'',v=>{t.suffix=v;changed();})));}if(t.type==='join'){sourceEditor(t,token.body);token.body.append(label(scText('الحقل'),fieldPicker(t.ref,r=>mutate(()=>{t.ref=r;}))),label(scText('الفاصل'),input(t.separator||'، ',v=>{t.separator=v;changed();})));filterEditor(t,token.body);}token.body.append(button(scText('حذف العنصر النصي'),()=>mutate(()=>{b.content.splice(tokenIndex,1);tokenIndex=null;})));right.append(token.section);}

if(b.content){const inline=propertySection(scText('إدراج داخل النص'),'inline',false),browser=el('div','','writer-fields'),search=input('',v=>browser.querySelectorAll('[data-label]').forEach(n=>n.hidden=!displayLabel(n.dataset).includes(v.toLowerCase())),'search');search.placeholder=scText('ابحث في الحقول…');inline.body.append(search);for(const category of schema()?.categories||[]){const d=el('details');d.open=false;d.append(el('summary',displayLabel(category)));for(const f of fields().filter(f=>f.category_id===category.id)){const n=button(displayLabel(f).split(' / ').at(-1),()=>insertToken({type:'field',ref:ref(f),empty:'—'}));n.dataset.label=f.label.toLowerCase();d.append(n);}browser.append(d);}inline.body.append(browser);const chips=el('div','','writer-property-command-grid');for(const p of model.parameters)chips.append(button('◈ '+displayLabel(p),()=>insertToken({type:'parameter',id:p.id})));chips.append(button(scText('تاريخ اليوم'),()=>insertToken({type:'system',name:'date'})),button(scText('رقم العنصر'),()=>insertToken({type:'system',name:'index'})),button(scText('عدد العناصر'),()=>insertToken({type:'system',name:'total'})),button(scText('العنصر الأول؟'),()=>insertToken({type:'system',name:'first'})),button(scText('العنصر الأخير؟'),()=>insertToken({type:'system',name:'last'})));if(['header','footer','first_header','first_footer'].includes(zone))chips.append(button(scText('رقم الصفحة'),()=>insertToken({type:'system',name:'current_page'})),button(scText('عدد الصفحات'),()=>insertToken({type:'system',name:'total_pages'})));chips.append(button(scText('ضم قيم البطاقات'),()=>insertToken({type:'join',source:{kind:'current_cards'},separator:'، '})),button(scText('حساب داخل النص'),()=>insertToken({type:'calculation',calculation:{kind:'aggregate',source:{kind:'profiles'},op:'count'}})));inline.body.append(chips);right.append(inline.section);}

const element=propertySection(scText('إعدادات العنصر'),'element',true);let hasElementSettings=false;
if(b.type==='section'||b.type==='heading'){hasElementSettings=true;element.body.append(check(scText('تضمين في الفهرس'),b.toc!==false,v=>mutate(()=>{b.toc=v;})),label(scText('المستوى'),choose(b.level||1,[[1,'1'],[2,'2'],[3,'3']],v=>mutate(()=>{b.level=Number(v);}))),check(scText('بدء صفحة جديدة'),b.new_page,v=>mutate(()=>{b.new_page=v;})));}
if(b.type==='row'){hasElementSettings=true;b.cells.forEach((c,i)=>element.body.append(label(scText('نسبة الخلية ')+(i+1),input(c.weight,v=>{c.weight=v;changed();},'number'))));if(b.cells.length<6)element.body.append(button(scText('إضافة خلية'),()=>mutate(()=>b.cells.push({weight:1,children:[]}))));}
if(b.type==='spacer'){hasElementSettings=true;element.body.append(label(scText('الارتفاع'),input(b.height||18,v=>{b.height=v;changed();},'number')));}
if(b.type==='image'){hasElementSettings=true;const upload=input('',()=>{},'file');upload.accept='image/png,image/jpeg';upload.onchange=()=>{const f=upload.files[0];if(!f)return;if(f.size>1000000){message(scText('الحد 1 ميغابايت للصورة.'),true);return;}const reader=new FileReader();reader.onload=()=>mutate(()=>{b.data=reader.result;});reader.readAsDataURL(f);};element.body.append(label(scText('صورة محلية فقط'),upload),label(scText('العرض بالنقاط'),input(b.width||150,v=>{b.width=v;changed();},'number')));}
if(b.type==='repeat'){hasElementSettings=true;element.body.append(check(scText('صفحة جديدة لكل عنصر'),b.page_each,v=>mutate(()=>{b.page_each=v;})));}
if(b.type==='component'){hasElementSettings=true;element.body.append(label(scText('سياسة النسخة'),choose(b.version||'latest',[['latest',scText('أحدث نسخة جاهزة')],...(library.components||[]).filter(c=>c.component_id===b.component).map(c=>[c.id,scText('نسخة ')+c.number])],v=>mutate(()=>{b.version=v;}))));}
if(hasElementSettings)right.append(element.section);

if(['repeat','table','chart'].includes(b.type)){
 const data=propertySection(scText('البيانات والتصفية'),'data',true);
 sourceEditor(b,data.body);filterEditor(b,data.body);
 data.body.append(
  label(scText('حد صريح للصفوف (اختياري)'),input(b.limit,v=>{if(v===null)delete b.limit;else b.limit=v;changed();},'number')),
  label(scText('عند عدم وجود بيانات'),input(b.empty||scText('لا توجد بيانات.'),v=>{b.empty=v;changed();}))
 );
 const sorting=el('details','','writer-nested-section'),sortKey=(active||'')+':sorting';
 sorting.open=propertyOpenState.has(sortKey)?propertyOpenState.get(sortKey):true;
 sorting.addEventListener('toggle',()=>propertyOpenState.set(sortKey,sorting.open));
 sorting.append(el('summary',scText('الترتيب')));
 for(const sortItem of b.sort||[]){
  sorting.append(
   label(scText('الحقل'),fieldPicker(sortItem.ref,r=>mutate(()=>{sortItem.ref=r;}))),
   label(scText('الاتجاه'),choose(sortItem.direction,[['asc',scText('تصاعدي')],['desc',scText('تنازلي')]],v=>mutate(()=>{sortItem.direction=v;}))),
   button(scText('حذف ترتيب'),()=>mutate(()=>b.sort.splice(b.sort.indexOf(sortItem),1)))
  );
 }
 sorting.append(button(scText('إضافة ترتيب'),()=>mutate(()=>{b.sort||=[];b.sort.push({direction:'asc'});})));
 data.body.append(sorting);right.append(data.section);
}

if(b.type==='table'){const columns=propertySection(scText('أعمدة الجدول'),'columns',true);b.columns.forEach((c,i)=>{const box=tableColumnSection(displayLabel(c)||scText('عمود'),'column-'+i);box.body.append(label(scText('اسم العمود'),input(displayLabel(c),v=>{c.label=v;changed();})));if(c.calculation){box.body.append(el('p',scText('عمود محسوب في سياق الصف الحالي.'),'writer-hint'));calculationEditor(c.calculation,box.body);descriptionOption(c,box.body);box.body.append(button(scText('تحويل إلى حقل'),()=>mutate(()=>{delete c.calculation;delete c.row_number;})));}else if(c.row_number){box.body.append(el('p',scText('رقم الصف بعد التصفية والترتيب.'),'writer-hint'),button(scText('تحويل إلى حقل'),()=>mutate(()=>{delete c.row_number;})));}else box.body.append(label(scText('الحقل'),fieldPicker(c.ref,r=>mutate(()=>{c.ref=r;delete c.row_number;delete c.calculation;}))));box.body.append(label(scText('العرض النسبي'),input(c.width||1,v=>{c.width=v;changed();},'number')),label(scText('الإجمالي'),choose(c.total||'',[['',scText('بدون إجمالي')],...reducers()],v=>mutate(()=>{c.total=v;}))),button(scText('تحريك العمود يمينًا'),()=>mutate(()=>{const j=b.columns.indexOf(c);if(j>0)b.columns.splice(j-1,0,b.columns.splice(j,1)[0]);})),button(scText('حذف عمود'),()=>mutate(()=>b.columns.splice(b.columns.indexOf(c),1))));columns.body.append(box.section);});const columnActions=el('div','','writer-property-command-grid');columnActions.append(button(scText('إضافة حقل'),()=>mutate(()=>b.columns.push({label:scText('عمود جديد'),width:1}))),button(scText('إضافة عمود محسوب'),()=>mutate(()=>b.columns.push({label:scText('عمود محسوب'),width:1,calculation:{kind:'aggregate',source:{kind:'current_row'},op:'count'}}))),button(scText('رقم الصف'),()=>mutate(()=>b.columns.push({label:'#',row_number:true,width:1}))));columns.body.append(columnActions,label(scText('التجميع'),fieldPicker(b.group_by,r=>mutate(()=>{b.group_by=r;}))),button(scText('إلغاء التجميع'),()=>mutate(()=>{delete b.group_by;})));right.append(columns.section);}

if(b.type==='chart'){const chart=propertySection(scText('إعدادات الرسم البياني'),'chart',true);chart.body.append(label(scText('نوع الرسم'),choose(b.chart,[['bar',scText('أعمدة رأسية')],['horizontal',scText('أشرطة أفقية')],['line',scText('خطي')],['pie',scText('دائري')],['donut',scText('حلقي')],['stacked',scText('أعمدة مكدسة')],['stacked100',scText('مكدس 100%')]],v=>mutate(()=>{b.chart=v;}))),label(scText('الفئة'),fieldPicker(b.category,r=>mutate(()=>{b.category=r;}))),label(scText('القياس'),choose(b.measure.op,reducers(),v=>mutate(()=>{b.measure.op=v;}))));if(!['count','profile_count'].includes(b.measure.op))chart.body.append(label(scText('حقل القياس'),fieldPicker(b.measure.ref,r=>mutate(()=>{b.measure.ref=r;}))));chart.body.append(label(scText('تجميع التاريخ الميلادي'),choose(b.date_group||'',[['',scText('بدون')],['day',scText('يوم')],['week',scText('أسبوع')],['month',scText('شهر')],['quarter',scText('ربع سنة')],['year',scText('سنة')]],v=>mutate(()=>{b.date_group=v;}))),label(scText('السلسلة (اختياري)'),fieldPicker(b.series,r=>mutate(()=>{b.series=r;}))),label(scText('أعلى N فئات'),input(b.top_n,v=>{if(v===null)delete b.top_n;else b.top_n=v;changed();},'number')),check(scText('جمع الباقي في أخرى'),b.other!==false,v=>mutate(()=>{b.other=v;})));right.append(chart.section);}

if(['calculation','percentage'].includes(b.type)){const calc=propertySection(scText('الحساب'),'calculation',true);calculationEditor(b.calculation,calc.body);descriptionOption(b,calc.body);calc.body.append(button(scText('حفظ كحساب قابل لإعادة الاستخدام'),()=>{const d=modal(scText('حساب قابل لإعادة الاستخدام'));let title=scText('حساب جديد');d.append(label(scText('الاسم'),input(title,v=>{title=v;})),button(scText('حفظ'),()=>{mutate(()=>{const id=uid();model.calculations[id]={...clone(b.calculation),title};b.calculation={kind:'ref',id};});d.close();}));}));right.append(calc.section);}

const visibility=propertySection(scText('الظهور الشرطي'),'visibility',false);filterEditor(b,visibility.body,'when');right.append(visibility.section);
}
async function componentsDialog(){library=await call('list');const d=modal(scText('مكتبة المكونات القابلة لإعادة الاستخدام'));const box=el('main');const search=input('',v=>box.querySelectorAll('[data-title]').forEach(n=>n.hidden=!n.dataset.title.includes(v.toLowerCase())),'search');search.placeholder=scText('ابحث عن مكون…');d.append(search,box);const b=find()?.b;if(b&&b.type!=='component'){d.append(button(scText('حفظ العنصر المحدد كمكون جاهز'),async()=>{const t=clone(model);t.blocks=[clone(b)];t.header=[];t.footer=[];await call('component_save',{template:t,title:currentTitle(b),required_context:model.mode,kind:b.type});d.close();componentsDialog();}));}
const latest=new Map();for(const c of library.components||[])if(!latest.has(c.component_id)||latest.get(c.component_id).number<c.number)latest.set(c.component_id,c);for(const c of latest.values()){const row=el('section','','writer-version');row.dataset.title=c.title.toLowerCase();row.append(el('strong',c.title+' · '+c.kind+scText(' · نسخة ')+c.number),el('p',scText('السياق المطلوب: ')+c.required_context,'writer-hint'));for(const linked of [true,false])row.append(button(linked?scText('إدراج مرتبط'):scText('نسخة مستقلة'),()=>{if(c.schema_id!==model.schema_id){message(scText('هذا المكون ينتمي إلى تصميم آخر.'),true);return;}mutate(()=>{const nodes=linked?[{id:uid(),type:'component',component:c.component_id,version:'latest',title:c.title}]:clone(c.blocks);if(!linked)walk(nodes,n=>n.id=uid());const target=find();(target?.b.children||model[zone]).push(...nodes);active=nodes[0].id;});d.close();}));if(b&&b.type!=='component'&&c.schema_id===model.schema_id)row.append(button(scText('حفظ المحدد كنسخة جديدة لهذا المكون'),async()=>{const t=clone(model);t.blocks=[clone(b)];t.header=[];t.footer=[];await call('component_save',{template:t,title:c.title,component_id:c.component_id,kind:c.kind,required_context:c.required_context});d.close();componentsDialog();}));box.append(row);}}
async function settingsDialog(){library=await call('list');const current=library.settings?.[0],settings=clone(current?.settings||{font_size:11,margin:18,page_size:'A4',orientation:'portrait',max_profiles:5000});settings.page_size||='A4';settings.orientation||='portrait';const d=modal(scText('إعدادات التقارير العامة'));d.append(el('p',scText('تطبّق على المستندات الجديدة فقط. لا تعيد كتابة القوالب المستقلة الحالية.'),'writer-hint'),label(scText('حجم الصفحة الافتراضي'),choose(settings.page_size,[['A4','A4'],['A3','A3'],['Letter','Letter'],['Legal','Legal']],v=>{settings.page_size=v;})),label(scText('اتجاه الصفحة الافتراضي'),choose(settings.orientation,[['portrait',scText('عمودي')],['landscape',scText('أفقي')]],v=>{settings.orientation=v;})),label(scText('حجم النص الافتراضي'),input(settings.font_size,v=>{settings.font_size=v;},'number')),label(scText('الهوامش الافتراضية (مم)'),input(settings.margin,v=>{settings.margin=v;},'number')),label(scText('الحد الأقصى لملفات التشغيل'),input(settings.max_profiles,v=>{settings.max_profiles=v;},'number')),check(scText('اعتماد رأس وتذييل المستند الحالي للمستندات الجديدة'),false,v=>{if(v){settings.header=clone(model.header);settings.footer=clone(model.footer);}else{delete settings.header;delete settings.footer;}}),el('p',scText('العربية / RTL · خط DejaVu Sans المضمن. المخرجات واللقطات التاريخية محفوظة محليًا؛ لا تُحذف تلقائيًا.'),'writer-hint'),button(scText('حفظ الإعدادات'),async()=>{await call('settings_save',{settings,revision:current?.revision});library=await call('list');d.close();}));}
async function parametersDialog(){const d=modal(scText('معاملات التشغيل'));const content=el('main');d.append(content);function draw(){content.replaceChildren();for(const p of model.parameters){const row=el('section','','writer-version');row.append(label(scText('الاسم'),input(displayLabel(p),v=>{p.label=v;changed();})),label(scText('النوع'),choose(p.type,[['text',scText('نص')],['number',scText('رقم')],['date',scText('تاريخ')],['datetime',scText('تاريخ ووقت')],['boolean',scText('نعم / لا')],['choice',scText('اختيار')],['multi_choice',scText('اختيارات متعددة')],['profile',scText('ملف')],['profiles',scText('عدة ملفات')]],v=>{mutate(()=>{p.type=v;delete p.default;},false);draw();})),check(scText('مطلوب'),p.required,v=>{p.required=v;changed();}));if(p.type==='choice'||p.type==='multi_choice')row.append(label(scText('الخيارات (كل خيار في سطر)'),input((p.choices||[]).join('\n'),v=>{p.choices=v.split('\n').filter(Boolean);changed();},'textarea')));if(!['profiles','multi_choice','boolean'].includes(p.type))row.append(label(scText('القيمة الافتراضية'),input(p.default,v=>{p.default=v;changed();},p.type==='number'?'number':'text')));if(p.type==='number')row.append(label(scText('الحد الأدنى (اختياري)'),input(p.min,v=>{if(v===null)delete p.min;else p.min=v;changed();},'number')),label(scText('الحد الأقصى (اختياري)'),input(p.max,v=>{if(v===null)delete p.max;else p.max=v;changed();},'number')));row.append(button(scText('حذف المعامل'),()=>{mutate(()=>model.parameters.splice(model.parameters.indexOf(p),1),false);draw();}));content.append(row);}content.append(button(scText('إضافة معامل'),()=>{mutate(()=>model.parameters.push({id:uid(),label:scText('معامل جديد'),type:'text',required:true}),false);draw();}));}draw();d.addEventListener('close',()=>render());}
async function libraryDialog(){await save();library=await call('list');const d=modal(scText('الملفات والنسخ'));d.append(button(scText('مستند جديد'),()=>{d.close();starterDialog();}),button(scText('تنزيل JSON'),()=>download(JSON.stringify(model,null,2),model.title+'.json','application/json')),button(scText('استيراد JSON'),()=>{const f=input('',()=>{},'file');f.accept='.json';f.onchange=async()=>{try{const m=JSON.parse(await f.files[0].text());await call('validate',{template:m});await save();model=m;saved=null;active=null;epoch++;render();d.close();changed();}catch(e){message(e.message,true);}};f.click();}));const main=el('main');d.append(main,el('p',scText('قوالب Markdown القديمة محفوظة في مجلداتها الأصلية ولم تُحوّل تلقائيًا؛ لا يمكن ضمان تطابق نتائجها مع نموذج المستند الجديد.'),'writer-hint'));main.append(el('h3',scText('مسودات العمل')));for(const item of library.drafts)main.append(button(item.template.title,async()=>{await save();model=clone(item.template);saved=item;active=null;undo=[];redo=[];epoch++;render();validate();d.close();}));main.append(el('h3',scText('نسخ جاهزة غير قابلة للتعديل')));for(const v of library.versions){const line=el('section','','writer-version');line.append(el('strong',v.template.title+scText(' · نسخة ')+v.number),button(scText('استعادة إلى المسودة'),async()=>{const current=library.drafts.find(x=>x.id===v.draft_id);const r=await call('restore',{version:v.id,revision:current?.revision});model=r.saved.template;saved=r.saved;active=null;epoch++;render();d.close();}));main.append(line);}main.append(el('p',scText('سجل التقارير المنشأة وملفات PDF موجود في جدول «سجل التصدير» الموحد في صفحة التصدير.'),'writer-hint'));}
function download(data,name,mime,base64=false){const raw=base64?Uint8Array.from(atob(data),c=>c.charCodeAt(0)):data,url=URL.createObjectURL(new Blob([raw],{type:mime})),a=el('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),5000);}
async function runDialog(preview,useReady=false){await save();library=await call('list');const ready=library.versions.filter(v=>v.draft_id===saved.id).sort((a,b)=>b.number-a.number);if(!preview&&!useReady&&(!ready.length||JSON.stringify(ready[0].template)!==JSON.stringify(model))){const prompt=modal(scText('اعتماد النسخة قبل الإنشاء'));prompt.append(el('p',scText('سيستخدم التقرير نسخة محفوظة ثابتة. يمكنك اعتماد المسودة الحالية الآن ثم متابعة اختيار الملفات.')),button(scText('اعتماد المسودة والمتابعة'),async()=>{await save();await call('publish',{id:saved.id,revision:saved.revision});prompt.close();await runDialog(false);}));if(ready.length)prompt.append(button(scText('استخدام آخر نسخة جاهزة دون التعديلات'),()=>{prompt.close();runDialog(false,true);}));return;}
const d=modal(preview?scText('معاينة المسودة باستخدام PDF الفعلي'):scText('إنشاء تقرير من نسخة جاهزة'));let version=ready[0]?.id,t=preview?model:ready[0].template,step=0,params={},selected=new Set(),all=true,query='',offset=0,output='combined',strict=true,preflight=null,filename=[{type:'text',text:t.title}],prompt=[],presetId='';
const nav=el('nav'),body=el('main'),notice=el('p','','writer-hint');const actions=el('div','','dialog-actions writer-run-actions');d.append(nav,body,notice,actions);notice.setAttribute('role','status');const base=()=>({...preview?{template:t}:{version},parameters:params,selection:all?{query}:{ids:[...selected]},output,strict,filename});
function redraw(){nav.replaceChildren();[scText('المعاملات'),scText('الملفات'),scText('المخرجات'),scText('المراجعة')].forEach((s,i)=>nav.append(button((i===step?'● ':'')+s,()=>{step=i;redraw();})));body.replaceChildren();notice.textContent='';actions.replaceChildren();const back=button(scText('السابق'),()=>{step--;redraw();});back.disabled=step===0;actions.append(back,el('span',scText('الخطوة ')+(step+1)+scText(' من 4'),'writer-hint'));if(step<3){const next=button(step===2?scText('التالي: مراجعة وإنشاء'):scText('التالي'),()=>{step++;redraw();});next.classList.replace('button-secondary','button-primary');actions.append(next);}
if(step===0){if(!preview)body.append(label(scText('النسخة الجاهزة'),choose(version,ready.map(v=>[v.id,scText('نسخة ')+v.number+' · '+v.updated_at]),id=>{version=id;t=ready.find(v=>v.id===id).template;params={};presetId='';redraw();})));if((library.presets||[]).length)body.append(label(scText('إعداد تشغيل محفوظ (اختياري)'),choose(presetId,[['',scText('بدون')],...(library.presets||[]).map(p=>[p.id,p.title])],id=>{presetId=id;const p=(library.presets||[]).find(x=>x.id===id);if(p){params=clone(p.config.parameters||{});selected=new Set(p.config.selection?.ids||[]);all=!p.config.selection?.ids;output=p.config.output||'combined';strict=p.config.strict!==false;prompt=clone(p.config.prompt||[]);}redraw();})));for(const p of t.parameters){let control;if(p.type==='boolean')control=choose(String(params[p.id]??p.default??''),[['',scText('اختر')],['true','نعم'],['false','لا']],v=>{params[p.id]=v==='true';});else if(p.type==='choice')control=choose(params[p.id]??p.default??'',[['',scText('اختر')],...(p.choices||[]).map(x=>[x,x])],v=>{params[p.id]=v;});else control=input(params[p.id]??p.default??'',v=>{params[p.id]=['profiles','multi_choice'].includes(p.type)?v.split(/[,،\n]/).map(x=>x.trim()).filter(Boolean):v;},p.type==='number'?'number':p.type==='date'?'date':p.type==='datetime'?'datetime-local':'text');body.append(label(displayLabel(p)+(p.required?' *':''),control),check(scText('إعادة طلب ')+displayLabel(p)+scText(' عند تحميل إعداد التشغيل'),prompt.includes(p.id),v=>{prompt=v?[...prompt,p.id]:prompt.filter(id=>id!==p.id);}));}if(!t.parameters.length)body.append(el('p',scText('لا توجد معاملات لهذا المستند.')));}
if(step===1){body.append(check(scText('كل الملفات المطابقة (بدون اقتطاع)'),all,v=>{all=v;redraw();}),label(scText('بحث الملفات'),input(query,v=>{query=v;offset=0;clearTimeout(searchTimer);searchTimer=setTimeout(loadProfiles,250);},'search')),el('p',scText('المحدد يدويًا: ')+selected.size,'writer-hint'));const list=el('div');list.id='writer-profile-list';body.append(list);loadProfiles();}
if(step===2){body.append(label(scText('بادئة اسم الملف'),input(filename[0]?.text||'',v=>{filename[0]={type:'text',text:v};})),label(scText('إضافة حقل إلى اسم الملف'),choose('',[['',scText('اختر حقلًا')],...(t.mode==='per_profile'?fields().filter(f=>!f.repeated).map(f=>[f.id,displayLabel(f)]):[])],id=>{const f=fields().find(f=>f.id===id);if(f){filename.push({type:'text',text:' - '},{type:'field',ref:ref(f),required:true});notice.textContent=scText('اسم الملف: ')+filename.map(x=>x.text||'['+tokenName(x)+']').join('');}})),label(scText('إضافة معامل إلى اسم الملف'),choose('',[['',scText('اختر معاملًا')],...t.parameters.map(p=>[p.id,displayLabel(p)])],id=>{if(id){filename.push({type:'text',text:' - '},{type:'parameter',id});notice.textContent=scText('اسم الملف: ')+filename.map(x=>x.text||'['+tokenName(x)+']').join('');}})),button(scText('إعادة ضبط الاسم'),()=>{filename=[{type:'text',text:t.title}];redraw();}),label(scText('المخرج'),choose(output,[['combined',scText('PDF واحد مجمّع')],['separate',scText('PDF منفصل لكل ملف')],['zip',scText('ZIP للملفات المنفصلة')]],v=>{output=v;})),check(scText('تشغيل صارم: أي خطأ يمنع الاكتمال'),strict,v=>{strict=v;}),el('p',scText('الملفات المتكررة الأسماء تحصل على لاحقة آمنة. التقارير والسجل يحتفظان بنسخة البيانات المستخدمة.'),'writer-hint'));}
if(step===3){const review=el('section','','writer-review');review.append(el('h3',scText('مراجعة التشغيل')));for(const [k,v] of [[scText('التقرير'),t.title],[scText('الوضع'),t.mode==='per_profile'?scText('تقرير لكل ملف'):scText('تقرير مجموعة')],[scText('الملفات'),all?scText('كل الملفات المطابقة'):selected.size+scText(' ملف محدد')],[scText('المخرج'),({combined:scText('PDF واحد مجمّع'),separate:scText('PDF منفصل لكل ملف'),zip:scText('ZIP للملفات المنفصلة')})[output]],[scText('معالجة الأخطاء'),strict?scText('صارمة'):scText('متسامحة')]]){const row=el('div','','writer-review-row');row.append(el('span',k),el('strong',String(v)));review.append(row);}body.append(review,el('p',preview?scText('المعاينة تستخدم المسودة الحالية ولا تضيف سجلًا جديدًا.'):scText('الإنشاء يستخدم النسخة الجاهزة فقط، وستظهر النتيجة في سجل التصدير الموحد.'),'writer-hint'),button(scText('فحص مسبق'),async()=>{try{preflight=await call('preflight',base());notice.textContent=preflight.documents+scText(' مستند / ')+preflight.profiles+scText(' ملف. ')+preflight.errors.map(e=>(e.profile||'')+': '+e.message).join(' · ');}catch(e){notice.textContent=e.message;}}),button(preview?scText('فتح معاينة PDF'):scText('بدء الإنشاء'),async()=>{try{preflight=await call('preflight',base());if(strict&&preflight.errors.length){notice.textContent=preflight.errors.map(e=>e.message).join('\n');return;}notice.textContent=scText('جارٍ التحضير…');const r=await call(preview?'preview':'run',base());if(preview){const pdf=modal(scText('معاينة PDF محلية')),frame=el('iframe'),bytes=Uint8Array.from(atob(r.pdf),c=>c.charCodeAt(0)),blob=new Blob([bytes],{type:'application/pdf'}),url=URL.createObjectURL(blob);pdf.classList.add('writer-pdf-preview-dialog');frame.title=scText('معاينة التقرير المحلية');frame.src=url;const previewActions=el('div','','writer-preview-actions'),safeName=((t.title||'report').replace(/[\\/:*?"<>|]+/g,'-').trim()||'report')+'.pdf',downloadButton=button(scText('تنزيل PDF'),()=>download(r.pdf,safeName,'application/pdf',true));downloadButton.classList.replace('button-secondary','button-primary');previewActions.append(downloadButton,el('span',scText('المعاينة والملف محليان بالكامل.'),'writer-hint'));pdf.append(previewActions,frame);pdf.addEventListener('close',()=>URL.revokeObjectURL(url));}else{d.close();watchRun(r.run.id);}}catch(e){notice.textContent=e.message;}}),button(scText('حفظ هذه الإعدادات للتشغيل المتكرر'),async()=>{await call('preset_save',{title:t.title,config:{...base(),prompt}});library=await call('list');notice.textContent=scText('حُفظ إعداد التشغيل. ستجده في خطوة المعاملات في المرة القادمة.');}));}}
let searchTimer;async function loadProfiles(){try{const response=await api({action:'profiles',schema_ids:[t.schema_id],query,offset});const list=body.querySelector('#writer-profile-list');if(!list)return;list.replaceChildren(el('p',response.total+scText(' ملف مطابق')));for(const p of response.profiles){const row=check(p.id+' · '+p.description,all||selected.has(p.id),v=>{all=false;if(v)selected.add(p.id);else selected.delete(p.id);});row.classList.add('writer-profile');list.append(row);}if(offset)list.append(button(scText('السابق'),()=>{offset=Math.max(0,offset-40);loadProfiles();}));if(response.has_more)list.append(button(scText('التالي'),()=>{offset+=40;loadProfiles();}));}catch(e){notice.textContent=e.message;}}redraw();}
async function watchRun(id){const d=modal(scText('حالة الإنشاء'));const body=el('main');d.append(body);let timer;async function poll(){try{const {run}=await call('status',{id});body.replaceChildren(el('h3',({Queued:scText('في الانتظار'),Generating:scText('جارٍ الإنشاء'),Completed:scText('مكتمل'),Failed:scText('فشل'),Partial:scText('مكتمل جزئيًا'),Cancelled:scText('ملغى')})[run.state]),el('p',run.completed+' / '+run.total),el('p',scText('النسخة ')+run.version_number+' · '+run.author+' · '+run.updated_at));for(const err of run.errors||[])body.append(el('p',(err.profile||'')+' '+err.message));if(run.error)body.append(el('p',run.error));body.append(button(scText('تفسير البيانات والحسابات التاريخية'),()=>inspectRun(id)));for(const o of run.outputs||[])body.append(button(scText('تنزيل ')+o.name,async()=>{const f=await call('download',{id,name:o.name});download(f.data,f.name,f.name.endsWith('.zip')?'application/zip':'application/pdf',true);}));if(['Queued','Generating'].includes(run.state)){body.append(button(scText('إلغاء'),()=>call('cancel',{id})),el('p',scText('يمكن إغلاق هذه النافذة؛ يستمر الإنشاء ما دام تطبيق SchemaCraft يعمل.'),'writer-hint'));timer=setTimeout(poll,1500);}else if(typeof loadExportHistory==='function'){await loadExportHistory();}}catch(e){body.append(el('p',e.message));}}d.addEventListener('close',()=>clearTimeout(timer));poll();}
async function inspectRun(id){const r=await call('inspect',{id});const d=modal(scText('تفسير التشغيل — اللقطة التاريخية'));d.append(el('p',scText('هذه النتائج من البيانات المحفوظة وقت الإنشاء، وليست من المصنف الحالي.'),'writer-hint'));const main=el('main');d.append(main);for(const item of r.documents){main.append(el('h3',item.profile||scText('تقرير المجموعة')));for(const trace of item.trace){const section=el('section','','writer-version');section.append(el('p',trace.warning||trace.note||(trace.calculation?scText('الحساب: ')+(reducers().find(x=>x[0]===trace.calculation.op)?.[1]||trace.calculation.kind):scText('عنصر المستند: ')+trace.element)));if(trace.value!==undefined)section.append(el('strong',scText('النتيجة: ')+(trace.value??scText('غير معرّفة'))));if(trace.matched_rows!==undefined||trace.rows!==undefined)section.append(el('p',scText('الصفوف المطابقة: ')+(trace.matched_rows??trace.rows)));if(trace.profiles)section.append(el('p',scText('الملفات المساهمة: ')+trace.profiles.join('، ')));main.append(section);}}main.append(el('p',r.profiles.length+scText(' ملفًا محلولًا · ')+Object.keys(r.component_versions).length+scText(' مكوّن مرتبط ثابت النسخة')),button(scText('تنزيل تفسير ولقطة هذا الجزء JSON'),()=>download(JSON.stringify(r,null,2),'report-explanation.json','application/json')));}
async function init(){if(initializing)return initializing;if(loaded)return;initializing=(async()=>{try{catalog=(await api({action:'catalog'})).schemas;library=await call('list');saved=library.drafts.at(-1)||null;model=saved?clone(saved.template):fresh();loaded=true;render();renderLandingOverview();validate();landingStatus.textContent=saved?model.title+scText(' · متابعة المسودة المحفوظة'):scText('ابدأ مستندًا جديدًا في نافذة مستقلة.');}catch(e){loaded=false;message(e.message,true);}finally{initializing=null;}})();return initializing;}
new MutationObserver(()=>{if(!host.hidden)init();}).observe(host,{attributes:true,attributeFilter:['hidden']});if(!host.hidden)init();
document.addEventListener('keydown',e=>{if(!editor.open||!model||[...document.querySelectorAll('dialog[open]')].at(-1)!==editor)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save().catch(err=>message(err.message,true));}});
window.SchemaCraftWriterHasPendingChanges = () => Boolean(timer || closingEditor);
window.addEventListener('beforeunload',e=>{if(timer){e.preventDefault();e.returnValue='';}});
})();
