const fs=require('fs'),os=require('os'),path=require('path'),assert=require('node:assert/strict'),{spawn,execFileSync}=require('child_process');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),out=process.env.REPORT_TEST_OUTPUT||'/tmp/integrated-workspace-qa',data=fs.mkdtempSync(path.join(os.tmpdir(),'schemacraft-integrated-'));
fs.mkdirSync(out,{recursive:true});
const schema=JSON.parse(execFileSync(process.env.CODEX_PRIMARY_RUNTIME_PYTHON,['-c',"import json,sys;sys.path.insert(0,'tests');from test_backend import configured_schema;print(json.dumps(configured_schema()))"],{cwd:root,encoding:'utf8'}));
for(const c of schema.categories)for(const f of c.fields)if(f.type==='checkbox'){f.checkbox_true_label='معتمد';f.checkbox_false_label='غير معتمد';}
fs.writeFileSync(path.join(data,'schema.json'),JSON.stringify(schema));
const server=spawn(process.env.CODEX_PRIMARY_RUNTIME_PYTHON,[root+'/tests/test_server.py',data,'--builder','--workspace'],{cwd:root,stdio:['ignore','pipe','pipe']});
let browser,serverErrors='';server.stderr.on('data',d=>serverErrors+=d);
(async()=>{try{
const port=await new Promise((resolve,reject)=>{let text='';const timer=setTimeout(()=>reject(Error(serverErrors||'server timeout')),15000);server.stdout.on('data',d=>{text+=d;const m=text.match(/PORT=(\d+)/);if(m){clearTimeout(timer);resolve(m[1]);}});server.once('exit',()=>{clearTimeout(timer);reject(Error(serverErrors));});});
console.log('Server ready');browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-gpu']});console.log('Browser ready');const page=await browser.newPage({viewport:{width:1550,height:1120}});const errors=[];page.on('pageerror',e=>errors.push(e.message));console.log('Opening application');await page.goto('http://127.0.0.1:'+port+'/');console.log('Waiting for operator prompt');await page.waitForSelector('#audit-user-dialog[open]');await page.locator('#audit-user-input').fill('مستخدم الاختبار');await page.locator('#confirm-audit-user').click();await page.waitForSelector('#app-status.status-ready',{state:'attached'});
console.log('Application ready');await page.locator('#builder-mode-button').click();await page.locator('#builder-view').waitFor({state:'visible'});
const field=page.locator('#builder-categories .builder-preview-field').filter({has:page.locator('input:not([type="checkbox"]):not([type="file"])')}).first();const name=field.locator('[data-preview-select]');
await name.hover();await page.waitForTimeout(350);assert.equal(await page.locator('#app-hover-card').isVisible(),false,'field label does not show a hover card');
await field.locator('input:not([type="checkbox"]):not([type="file"])').first().hover({force:true});await page.waitForFunction(()=>!document.querySelector('#app-hover-card').hidden);await name.click();assert.equal(await page.locator('#app-hover-card').isVisible(),false);await field.locator('[data-builder-action="edit-field"]').click();await page.locator('#field-dialog').waitFor();assert.equal(await page.locator('#field-category-name').evaluate(e=>e.tagName),'SELECT');await page.screenshot({path:out+'/field-category-dialog.png'});await page.locator('#field-dialog [data-close-dialog]').first().click();
assert.equal(await page.locator('#builder-categories .checkbox-meaning').count(),0);
await page.screenshot({path:out+'/builder-controls.png'});
await page.locator('#export-page-button').click();
await page.locator('[data-export-schema-tab]').first().click();
await page.locator('[data-export-mode="advanced"]').click();
await page.locator('#advanced-export-panel').waitFor({state:'visible'});
assert.equal(await page.locator('dialog#report-studio').isVisible(),false);
assert.equal(await page.locator('#studio-workspace-slot').count(),0);
await page.screenshot({path:out+'/advanced-report-page.png'});
await page.getByRole('button',{name:'فتح الاستوديو المرئي',exact:true}).click();
await page.locator('dialog#report-studio[open]').waitFor();
await page.waitForFunction(()=>!document.querySelector('#report-studio .studio-body').inert);
await page.screenshot({path:out+'/report-dialog.png'});
await page.locator('#studio-document-title').fill('عنوان يحتفظ به التقرير');
await page.getByRole('button',{name:'إغلاق الاستوديو',exact:true}).click();
await page.locator('dialog[open]').last().getByRole('button',{name:'اعتماد',exact:true}).click();
await page.locator('#report-studio').waitFor({state:'hidden'});
await page.getByRole('button',{name:'فتح الاستوديو المرئي',exact:true}).click();
await page.locator('dialog#report-studio[open]').waitFor();
assert.equal(await page.locator('#studio-document-title').inputValue(),'عنوان يحتفظ به التقرير');
await page.setViewportSize({width:960,height:820});
await page.screenshot({path:out+'/report-dialog-narrow.png'});
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'page fits narrow viewport');
assert.deepEqual(errors,[]);
console.log('Restored report page and modal, retained edits, narrow layout and Builder controls passed.');
}finally{if(browser)await browser.close();server.kill();fs.rmSync(data,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
