#!/usr/bin/env python3
"""Assemble SchemaCraft's browser assets from the modular frontend source."""

from __future__ import annotations

import base64
import json
import re
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
APP_DIR = PROJECT_DIR / "app"
SOURCE_DIR = APP_DIR / "src"
INCLUDE_PATTERN = re.compile(r"<!--\s*@include\s+([^\s]+)\s*-->")
UI_TEXT_PATH = SOURCE_DIR / "ui_text.json"
BUILD_SCRIPT_PATH = PROJECT_DIR / "build-windows-cli.bat"
LIFECYCLE_ASSETS = (
    "lifecycle/lifecycle.css",
    "lifecycle/startup.html",
    "lifecycle/startup.js",
    "lifecycle/closing.html",
    "lifecycle/closing.js",
    "viewer/attachment-viewer.html",
    "viewer/attachment-viewer.css",
    "viewer/attachment-viewer.js",
)


def source_text(relative_path: str) -> str:
    path = SOURCE_DIR / relative_path
    if not path.is_file():
        raise FileNotFoundError(f"Missing frontend source file: {path}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def manifest_entries(name: str) -> list[str]:
    return [
        line.strip()
        for line in source_text(name).splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def assemble_html() -> str:
    shell = source_text("shell.html")

    def include(match: re.Match[str]) -> str:
        return source_text(match.group(1)).rstrip()

    assembled = INCLUDE_PATTERN.sub(include, shell)
    unresolved = INCLUDE_PATTERN.findall(assembled)
    if unresolved:
        raise RuntimeError(f"Unresolved HTML includes: {', '.join(unresolved)}")
    # Keep the assembled files in their canonical wording.  The application
    # server applies ``app/ui_text.json`` when each text asset is requested,
    # which means operators can change wording without rebuilding the app.
    return assembled.rstrip() + "\n"


def assemble_manifest(name: str, banner: str) -> str:
    chunks = []
    for relative_path in manifest_entries(name):
        chunks.append(f"/* {relative_path} */\n{source_text(relative_path).rstrip()}\n")
    content = f"/* {banner} — generated by build_frontend.py. */\n" + "\n".join(chunks)
    return content


def ui_text_catalog() -> dict[str, str]:
    """Return editable non-schema UI labels used during frontend assembly."""

    payload = json.loads(UI_TEXT_PATH.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise TypeError("app/src/ui_text.json must contain a JSON object")
    catalog: dict[str, str] = {}
    for source, replacement in payload.items():
        if source.startswith("_"):
            continue
        if not isinstance(source, str) or not isinstance(replacement, str):
            raise TypeError("Every UI text entry must map one string to another string")
        if not source:
            raise ValueError("UI text keys cannot be empty")
        catalog[source] = replacement
    return catalog


def localize_ui_text(content: str) -> str:
    """Apply the catalog without letting one replacement cascade into another."""

    catalog = ui_text_catalog()
    placeholders: list[tuple[str, str]] = []
    localized = content
    for index, source in enumerate(sorted(catalog, key=len, reverse=True)):
        token = f"__SC_UI_TEXT_{index:04d}__"
        if token in localized:
            raise ValueError(f"Reserved UI text token already exists: {token}")
        localized = localized.replace(source, token)
        placeholders.append((token, catalog[source]))
    for token, replacement in placeholders:
        localized = localized.replace(token, replacement)
    return localized


def embedded_application_icon() -> bytes:
    """Decode the same icon payload consumed by the Windows executable build."""

    lines = BUILD_SCRIPT_PATH.read_text(encoding="utf-8").splitlines()
    try:
        start = lines.index("::BEGIN_ICON_BASE64") + 1
        end = lines.index("::END_ICON_BASE64")
    except ValueError as exc:
        raise RuntimeError("The embedded Windows icon markers are missing") from exc
    encoded = "".join(line[2:] for line in lines[start:end] if line.startswith("::"))
    content = base64.b64decode(encoded, validate=True)
    if not content.startswith(b"\x00\x00\x01\x00"):
        raise RuntimeError("The embedded Windows icon is not a valid ICO payload")
    return content


def write_if_changed(path: Path, content: str) -> None:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8", newline="\n")


def write_bytes_if_changed(path: Path, content: bytes) -> None:
    if path.is_file() and path.read_bytes() == content:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)


def main() -> None:
    write_bytes_if_changed(
        APP_DIR / "assets" / "schemacraft.ico",
        embedded_application_icon(),
    )
    write_if_changed(APP_DIR / "index.html", assemble_html())
    write_if_changed(
        APP_DIR / "ui_text.json",
        UI_TEXT_PATH.read_text(encoding="utf-8").rstrip() + "\n",
    )
    write_if_changed(
        APP_DIR / "app.js",
        assemble_manifest("javascript.manifest", "SchemaCraft JavaScript bundle"),
    )
    write_if_changed(
        APP_DIR / "styles.css",
        assemble_manifest("styles.manifest", "SchemaCraft stylesheet bundle"),
    )
    write_if_changed(APP_DIR / "workspace.js", source_text("core/workspace.js"))
    for relative_path in LIFECYCLE_ASSETS:
        write_if_changed(
            APP_DIR / Path(relative_path).name,
            source_text(relative_path),
        )
    print("Frontend assets assembled successfully.")


if __name__ == "__main__":
    main()
